### ISSUE TITLE
Inline schemas still being generated with schema.GenerateInline = false

### ISSUE THREAD

**Issue by adahl5** [danielgtaylor/huma#102]
I'm working on a project and have run into issues generating schemas that include references to other schemas. Rather than trying to explain my schemas and structure, I used the [bookstore example](https://github.com/danielgtaylor/huma/blob/v1.14.0/examples/bookstore/bookstore.go) and was able to reproduce the issue without modifying the code.

---

[Gist of the openapi.json file generated by the bookstore example with no modifications to the code](https://gist.github.com/adahl5/1e70cc1db1d68aacdf80c98b83650a82)

I ran into the first issue by just running the code without modification. Two Book schemas are generated (Book and Book2), Book has the `$schema` property and Book2 does not. Additionally, Book2 is used as the `$ref` schema for the `BookList` schema.

As shown in the next two schemas, adding `app.DisableSchemaProperty()` removed the Book2 schema but did not resolve the issue. 

---

[openapi.json after adding a call to app.DisableSchemaProperty()](https://gist.github.com/adahl5/251a4ec6affe02649211e2f5d23df92f)

Now, the real issue. The Genre.Books array uses an inline Book schema that is identical to the top-level Book schema. It's the same issue I'm having with my project. Structs used in other structs are generated inline rather than as references. I'm wondering if this has something to do with how the model is provided to the responses.OK().Model function because the BookList schema is properly generated as an array of the Book schema (using the `$ref` property). All the attached schemas include this issue. 

---

[openapi.json after adding app.DisableSchemaProperty() and schema.GenerateInline = false](https://gist.github.com/adahl5/c74c7833d52e059713842890774d706b)

As far as I can tell, the only difference between the 2nd and 3rd schema is that only the GenerateInline = false schema includes a `ErrorDetail` schema.

I'm not sure what to do here. I manually modified the openapi.json file to replace the incorrectly generated inline schemas with references to the correct schemas and it solved the issues I was having downstream when generating SDKs. I could continue with this manual solution, but I'm still developing the application and would have to repeat the process every time I make an update to the backend. Please let me know if you need me to provide more information about the issue.

**Comment by danielgtaylor** [comment]
I would be curious how things look with the Huma v2 beta, which has a completely new registry & schema generator.

**Comment by danielgtaylor** [comment]
Going to close this - please reopen if the issue happens in Huma v2.
