### ISSUE TITLE
Operation Specific Security Policies

### ISSUE THREAD

**Issue by mt35-rs** [danielgtaylor/huma#108]
Currently, it appears that `huma` only provides the ability to specify the `security` scheme for the entire API via `router.GatewayAuthCode(...)` and `router.SecurityRequirement(...)`.  While [OpenAPI 3.0.x allows for a security scheme to be specified per operation](https://swagger.io/docs/specification/authentication/):

> After you have defined the security schemes in the securitySchemes section, you can apply them to the whole API or individual operations by adding the security section on the root level or operation level, respectively

...it appears that `huma` only supports specifying the security scheme at the global level.  This is substantiated by looking at [the definition of the `Operation` struct](https://github.com/danielgtaylor/huma/blob/main/operation.go#L47-L61) (which seems to contain no fields capable of storing the security scheme information).

Is this all accurate or am I missing something?

Assuming this assessment is correct, then I'd like to suggest adding support for operation specific security schemes.

**Comment by danielgtaylor** [comment]
This is now possible in the v2 betas, so I'm going to close the request. You now have full access to the OpenAPI including extensions.
