### ISSUE TITLE
How do you switch to v2?

### ISSUE THREAD

**Issue by harry1453** [danielgtaylor/huma#109]
I have tried `go get github.com/danielgtaylor/huma@v2` but I get an error: `no matching versions for query "v2"`. I think this is because when you ask for version "v2", go looks for tags since this looks like a version number, and errors when it doesn't find any. It doesn't bother looking for branches.

I can't figure out the correct `replace` directive to use. Please can you post what the replace directive you are using is?

**Comment by nickajacks1** [comment]
It doesn't seem v2 is ready for a production setting, but if you want to try it out, you will need to `replace` with a local directory. For example, clone this repo to a location on disk, check out v2, then add `replace github.com/danielgtaylor/huma => /path/to/huma` to your `go.mod`.

It might also be possible to use vendoring, not sure.

**Comment by danielgtaylor** [comment]
The v2 beta has been released, so you should be able to directly install it now:

```sh
$ go get github.com/danielgtaylor/huma/v2
```

You can check the main branch README for details and examples. More to come but please let me know if you have any initial feedback!
