### ISSUE TITLE
Validating JSON outside of a request

### ISSUE THREAD

**Issue by nickajacks1** [danielgtaylor/huma#121]
The validation is great, and it would be nice to be able to use it outside the context of a request (e.g., JSON file validation). However, the public interface is somewhat awkward due to the included optimizations.
Would it be in the spirit of things to add a simplified interface for generic schema validation? Or does supporting such a feature go out of the scope of Huma?

A few details that could potentially be abstracted away:
- The `Registry` parameter is used only if the schema is a reference (or is a parent to one, recursively)
- The `PathBuffer` could potentially be made optional
- `ValidateMode` could have a default (or be ignored?)
- `ValidateResult` could implement `Error()` and be returned as an `error`

I feel like a lot of the extra details could be abstracted away without giving up the optimizations.
For example, a config/option struct could be used that provides reasonable defaults.

Another approach might be to create a wrapper function that simplifies use (or even just suggest that users create one themselves).

**Comment by danielgtaylor** [comment]
@nickajacks1 this is a great idea! Personally I think a simplified wrapper/utility function might help here, and if you don't like the defaults you can drop back down to using the registry/path-buffer/etc. I'm happy to review a PR for this, or if you tell me more about how you expect to use it (maybe with an example) I can implement on my side.

Small side note: the primary purpose is and always will be for validation of HTTP API requests, so while I like new use cases and such I would prefer to not negatively impact the performance of the intended and most common use case.

**Comment by nickajacks1** [comment]
Thanks for the prompt response.
Here's an approximation of what I'd like to do (with the current implementation):
```go
type MyThing struct {
	ID string `json:"id" format:"uuid"`
}

var thingType = reflect.TypeOf(MyThing{})

func validateThing(b []byte, reg huma.Registry) error {
	s := reg.Map()[thingType.Name()]

	var parsed any
	json.Unmarshal(b, &parsed)

	res := huma.ValidateResult{}
	huma.Validate(reg, s, huma.NewPathBuffer([]byte(""), 0), huma.ModeReadFromServer, parsed, &res)

	if len(res.Errors) > 0 {
		return errors.Join(res.Errors...)
	}
	return nil
}

func main() {
	r := fiber.New()
	api := humafiber.New(r, huma.DefaultConfig("Validate", "1.0.0"))
	api.OpenAPI().Components.Schemas.Schema(
		thingType,
		true,
		thingType.Name(),
	)
	b, _ := os.ReadFile("thing.json")
	err = validateThing(b,
		api.OpenAPI().Components.Schemas)
	if err != nil {
		panic("thing.json is not valid")
	}
}
```
Full example is here https://github.com/nickajacks1/huma/tree/main/examples/validate

In reality, I'd be using huma like normal with this side validation tacked on, but this example shows how the validation can be useful even outside of an Operation.

It's simple enough to make a wrapper for myself, but I had to peek into the source code to see how to properly use the Validate function.  If there are any others like me, I'd like to save them a little effort.  I'll write up a PR within the next couple weeks unless you'd like to take the wheel.

**Comment by danielgtaylor** [comment]
@nickajacks1 please have a look at #126 and let me know if that works or if you have any other improvements you'd like to see!
