### ISSUE TITLE
String Array Input Inconsistency

### ISSUE THREAD

**Issue by harryjph** [danielgtaylor/huma#130]
If my handler has an input:

```go
type Input struct {
    Names []string `query:"name"`
}
```

Then huma expects me to call my endpoint as `GET /endpoint?name=name1,name2`. However, the way the `/docs` page expects it to be called is `GET /endpoint?name=name1&name=name2`. Calling like this results in the handler being given `[]string{"name1"}` as its input - missing the second occurrence of the query parameter. This inconsistency means that we cannot test this endpoint using the `/docs` page.

We would prefer to be able to use the same query parameter name multiple times in the URL to build the array, like the docs page tries to do. Please could you add support for this to Huma?

**Comment by danielgtaylor** [comment]
Just wanted to let you know I merged a fix for the docs inconsistency, so it should now work.

> We would prefer to be able to use the same query parameter name multiple times in the URL to build the array, like the docs page tries to do. Please could you add support for this to Huma?

I don't have this implemented yet. It would require changing the code which parses query params to support parsing multiple of the same param name. It's doable but more work than I'm trying to take on before a 2.0.0 release. Happy to review/merge if someone else wants to take a look at supporting that.
