### ISSUE TITLE
Support nullable type

### ISSUE THREAD

**Issue by teleskop150750** [danielgtaylor/huma#137]
can I use your library for example with "[opt](https://github.com/aarondl/opt)" to support nullable fields?

**Comment by danielgtaylor** [comment]
This should theoretically be possible, but I don't think the correct JSON Schema type will get generated in the OpenAPI spec. I will think about how best to support such use-cases 🤔

**Comment by danielgtaylor** [comment]
@teleskop150750 I've opened up #145 with the ability to create and use custom types with support for proper JSON Schema. It won't let you use the `opt` library directly, but you can wrap its type and provide a `Schema(r huma.Registry) *huma.Schema` method and it will work with Huma, as in the example in the PR. Please take a look!
