### ISSUE TITLE
[gorilla/mux] Same route with different methods does not work

### ISSUE THREAD

**Issue by jonathanyuechun** [danielgtaylor/huma#179]
Adapter: gorrilla 

What i tried:

```md
Path := "/test/{ns}/name/{ok}
Vanilla gorrilla // both works but not when using huma
r.handle(path, fn1).method(http.delete)
r.handle(path, fn2).method(http.post)

```

**Comment by danielgtaylor** [comment]
@jonathanyuechun sorry about that, the gorilla/mux adapter wasn't as well tested as ones like Chi and Fiber. #180 should fix the issue and I can push out a patch release.

**Comment by danielgtaylor** [comment]
Released in https://github.com/danielgtaylor/huma/releases/tag/v2.0.1
