### ISSUE TITLE
Better support for offline

### ISSUE THREAD

**Issue by jonathanyuechun** [danielgtaylor/huma#181]
My use case is as follows:

I want to be able to generate an aggregated opeapi.yaml/json ( in 1 file)including its json schema.
Likewise, be able to generate aggregated jsonschema (in 1 file) and non aggregated ones (multiple files)

A cli or entrypoint that xan be called in a mai. Is needed.
=> be able to automate stuffs much more easily without pulling external tools
=> offline rendering of api specs

Suggestions : if possible provide a package/go module that can only do those things

**Comment by danielgtaylor** [comment]
@jonathanyuechun there is an example that shows how to output the OpenAPI file at https://github.com/danielgtaylor/huma/blob/main/examples/spec-cmd/main.go#L68-L76. You can do something similar for the individual schemas if needed. For example, if I modify the command like this:

```go
// Add a command to print the OpenAPI spec.
cli.Root().AddCommand(&cobra.Command{
	Use:   "openapi",
	Short: "Print the OpenAPI spec",
	Run: func(cmd *cobra.Command, args []string) {
		b, _ := yaml.Marshal(api.OpenAPI())
		fmt.Println(string(b))

		// Also print the individual schemas.
		for name, schema := range api.OpenAPI().Components.Schemas.Map() {
			fmt.Printf("Schema: %s\n", name)
			b, _ := yaml.Marshal(schema)
			fmt.Println(string(b))
		}
	},
})
```

I can then run `go ./examples/spec-cmd openapi` and get output for the OpenAPI yaml *and* each individual JSON Schema as well. I'll leave it as an exercise to the reader to write them out into files :smile:

**Comment by jonathanyuechun** [comment]
yes i think it does. gonna try it asap. i will let you know

**Comment by danielgtaylor** [comment]
Closing as I think this is solved, but feel free to re-open if needed!
