### ISSUE TITLE
Allow file upload limit to be defined by the user

### ISSUE THREAD

**Issue by JanRuettinger** [danielgtaylor/huma#205]
When you want to access data from the request through MultipartForm, huma context exposed a function called `GetMultipartForm` that parses the MultipartForm and returns it. The issue is that we are limited to the predefined limit of `8*1024` as shown in the snippet below.  

```
func (c *chiContext) GetMultipartForm() (*multipart.Form, error) {
	err := c.r.ParseMultipartForm(8 * 1024)
	return c.r.MultipartForm, err
}
```
[Link to code snippet](https://github.com/danielgtaylor/huma/blob/3a7da129f4dccc8191b614206f63ebca1fcced1e/adapters/humachi/humachi.go#L72C1-L72C1)

Can we allow the user to set this limit in the config when initializing the huma router?

**Comment by JanRuettinger** [comment]
What do you think about adding a parameter to the `GetMultipartForm` function that allows the user to set the upload limit?

```
func (c *chiContext) GetMultipartForm(uploadLimit int) (*multipart.Form, error) {
	err := c.r.ParseMultipartForm(uploadLimit)
	return c.r.MultipartForm, err
}
```

**Comment by danielgtaylor** [comment]
@JanRuettinger I'm trying to figure out what to do for this. Your suggestion would be a breaking change for the interface (which we should avoid). Adding another function that takes the argument is another possibility, but again that makes the `huma.Context` interface more complicated or makes you cast the context to see if it supports that new feature... 🤔 

Is it important that you configure this on a per-call basis? I'm thinking alternatively we expose it as a public value in the package so you can set it to whatever you like as the max, e.g. `var MultipartMaxMemory = 8 * 1024` and then you could do this in your code as part of service start up: `humachi.MultipartMaxMemory = 2 * 1024 * 1024`.

**Comment by JanRuettinger** [comment]
Yes agree, the proposed solution breaks the interface. 

Exposing the limit as a public value would solve the problem for me!
