### ISSUE TITLE
Integrity check for spotlight docs UI fails

### ISSUE THREAD

**Issue by JanRuettinger** [danielgtaylor/huma#215]
Three days ago the docs html page was changed in commit #https://github.com/danielgtaylor/huma/commit/1f47e92500b7f13d1446329a0041d1dbbcd3cbef. The docs page now specifies the **version of the spotlight** package and does an **integrity check**. 

### Before:
```
<script src="https://unpkg.com/@stoplight/elements/web-components.min.js"></script>
<link rel="stylesheet" href="https://unpkg.com/@stoplight/elements/styles.min.css" />
```
### Now:
```
<link href="https://unpkg.com/@stoplight/elements@8.0.0/styles.min.css" rel="stylesheet" />
<script src="https://unpkg.com/@stoplight/elements@8.0.0/web-components.min.js"
             integrity="sha256-yIhuSFMJJ6mp2XTUAb4SiSYneP3Qav8Uu+7NBhGJW5A="></script>
```

The integrity check fails for me so that the docs page doesn't load with the following error:

`Subresource Integrity: The resource 'https://unpkg.com/@stoplight/elements@8.0.0/web-components.min.js' has an integrity attribute, but the resource requires the request to be CORS enabled to check the integrity, and it is not. The resource has been blocked because the integrity cannot be enforced.`

### Workaround
My current workaround is to remove the integrity check as shown below:
```
<link href="https://unpkg.com/@stoplight/elements@8.0.0/styles.min.css" rel="stylesheet" />
<script src="https://unpkg.com/@stoplight/elements@8.0.0/web-components.min.js"></script>
```

Are more people running into this issue?

**Comment by qdongxu** [comment]
+1 :p

**Comment by danielgtaylor** [comment]
This should be fixed in `main` now, just FYI!
