### ISSUE TITLE
Cannot reuse structs with same name but different objects as Input

### ISSUE THREAD

**Issue by simonfr** [danielgtaylor/huma#219]
Hello,

I've 2 business objects in my project :
One for projects that I define as this (to be reusable for Input/Output) :
```
type Fields struct {
	Name      string `json:"name" maxLength:"30" example:"my-namespace" doc:"Name of the project"`
	Namespace string 
}

type IdFields struct {
	UUID string 
}

type FieldsWithId struct {
	IdFields
	Fields
}

type Output struct {
	Body FieldsWithId
}

type ListOutput struct {
	Body []FieldsWithId
}

type CreateInput struct {
	Body Fields
}
```

And one for the namespace I defined like this :
```
type Fields struct {
	Name    string
	Members []string 
}

type IdFields struct {
	UUID string 
}

type FieldsWithId struct {
	IdFields
	Fields
}

type Output struct {
	Body FieldsWithId
}

type ListOutput struct {
	Body []FieldsWithId
}

type CreateInput struct {
	Body Fields
}
```

And then, i'm using those as input in my handlers.
When I try to launch the app I've this error : `panic: duplicate name Fields does not match existing type. New type namespace.Fields, have existing types map[project.FieldsWithId:true huma.ErrorDetail:true project.Fields:true huma.ErrorModel:true]`
https://github.com/danielgtaylor/huma/blob/main/registry.go#L88

But is the any reason to forbid have 2 inputs with the same name ?

Simon

**Comment by danielgtaylor** [comment]
@simonfr does that hopefully answer your question? If not, please re-open this issue.
