### ISSUE TITLE
Sub routers and Grouping

### ISSUE THREAD

**Issue by thegeekywanderer** [danielgtaylor/huma#220]
I went through this issue #182 and I understand why huma doesn't support router groups and sub router mounting. But I can't figure out how to achieve something similar to the following chi implementation even after going through that issue:
```go
func main() {
    r := chi.NewRouter()
    
    r.Mount("/api", Versions())

    http.ListenAndServe("localhost:8080", r)
}

func Versions() chi.Router {
    r := chi.NewRouter()
    r.Mount("/v1", V1())
 // r.Mount("/v2", V2())
    return r    
}

func V1() chi.Router {
    r := chi.NewRouter()
    r.Mount("/user", User())
//  r.Mount("/posts", Post())
    return r
}

func User() chi.Router {
    r := chi.NewRouter()
    r.Route("/hello", func(r chi.Router){
        r.Get("/", hello)
    })
    return r
}

func hello(w http.ResponseWriter, r *http.Request) {
    w.Write([]byte("Hello"))
}
```

I want the generated documentation to be have multiple versions and I also want to have multiple groups underneath each versioned API.

**Comment by danielgtaylor** [comment]
@thegeekywanderer sorry for the delay on responding! Have you tried something like this?

```go
func main() {
	r := chi.NewRouter()

	api := humachi.New(r, huma.DefaultConfig("My API", "1.0.0"))

	Versions(api)

	http.ListenAndServe("localhost:8080", r)
}

func Versions(api huma.API) {
	V1(api)
	// V2(api)
}

func V1(api huma.API) {
	User(api, "/v1/user")
}

func User(api huma.API, prefix string) {
	huma.Register(api, huma.Operation{
		OperationID: "hello",
		Method:      http.MethodGet,
		Path:        prefix + "/hello",
	}, hello)

	// huma.Register(api, huma.Operation{
	// 	OperationID: "posts",
	// 	Method:      http.MethodGet,
	// 	Path:        prefix + "/posts",
	// }, posts)
}

type HelloOutput struct {
	Body struct {
		Message string `json:"message" doc:"Hello message"`
	}
}

func hello(ctx context.Context, input *struct{}) (*HelloOutput, error) {
	resp := &HelloOutput{}
	resp.Body.Message = "Hello!"
	return resp, nil
}
```

> I want the generated documentation to be have multiple versions and I also want to have multiple groups underneath each versioned API.

Can you elaborate on this? You can create groups by using OpenAPI tags and it'll group those operations by tag in the generated documentation.

**Comment by servernoj** [comment]
@thegeekywanderer 

I am not sure if that will help, but I am working on a similar setup (multi-version API) and have some progress (to my satisfaction).

https://github.com/servernoj/huma-demo

It uses `Gin` as a router, which should be pretty straightforward to replace with anything else.

Here are the logs for `v1`
```
restish :8001/api/v1/version
HTTP/1.1 200 OK
Content-Length: 5
Content-Type: text/plain; charset=utf-8
Date: Sat, 03 Feb 2024 02:39:52 GMT

1.0.0
```
and `v2`
```
restish :8001/api/v2/version
HTTP/1.1 200 OK
Content-Length: 5
Content-Type: text/plain; charset=utf-8
Date: Sat, 03 Feb 2024 02:39:57 GMT

2.0.0
```

**Comment by danielgtaylor** [comment]
I believe this is now answered, but please re-open or open a new issue if you are still having issues!

**Comment by s1moe2** [comment]
> I am not sure if that will help, but I am working on a similar setup (multi-version API) and have some progress (to my satisfaction).
> 
> https://github.com/servernoj/huma-demo


@servernoj can you make your sample/demo available again please?

**Comment by servernoj** [comment]
@s1moe2 I re-uploaded that demo repo.

You may also find this technique illustrated in the actual project at https://github.com/servernoj/quible-api/blob/dev/auth-service/main.go. Please consider it as my best effort to adopt Huma rather than a statement of showing the "right way".

**Comment by cardinalby** [comment]
Facing with the same problem I had to make a wrapper for Huma registration pipeline that allows me to create groups with custom prefixes, middlewares, transformers, etc.

[https://github.com/cardinalby/hureg](https://github.com/cardinalby/hureg)

This way you can work with Huma in a familiar way and easily migrate from other routers
