### ISSUE TITLE
Panic when using `example` or `enum` struct tag for OmittableNullable

### ISSUE THREAD

**Issue by ddl-ebrown** [danielgtaylor/huma#228]
I'm using the support for optional body fields as implemented in #145 

The OpenAPI spec is generated properly when using a definition like:
`Hash OmittableNullable[string] json:"hash,omitempty" doc:"Hash of the file contents of the artifact, when available"`

After adding the `example` struct tag like `example:"47944637b32facc94c1c49b32202b63e23b6ea7f225baa1d89868b3ff32d4a1e"`, a panic is generated. Similarly, a panic occurs when using an `enum` struct tag like `enum:"MD5,SHA-1,SHA-256,SHA-512"`

That same `example` struct tag works perfectly fine when the struct property is defined as `Hash string`.

```
panic: invalid tag for field 'Hash': invalid character 'b' after top-level value

goroutine 1 [running]:
github.com/danielgtaylor/huma/v2.jsonTagValue({{0x1033206fa, 0x4}, {0x0, 0x0}, {0x103386ec8, 0x103336880}, {0x103320700, 0x96}, 0x48, {0x140001a5058, ...}, ...}, ...)
	/Users/ethan.brown/go/pkg/mod/github.com/danielgtaylor/huma/v2@v2.3.0/schema.go:268 +0x828
github.com/danielgtaylor/huma/v2.jsonTag({{0x1033206fa, 0x4}, {0x0, 0x0}, {0x103386ec8, 0x103336880}, {0x103320700, 0x96}, 0x48, {0x140001a5058, ...}, ...}, ...)
	/Users/ethan.brown/go/pkg/mod/github.com/danielgtaylor/huma/v2@v2.3.0/schema.go:310 +0xcc
github.com/danielgtaylor/huma/v2.SchemaFromField({0x1033801a0?, 0x14000274540?}, {{0x1033206fa, 0x4}, {0x0, 0x0}, {0x103386ec8, 0x103336880}, {0x103320700, 0x96}, ...}, ...)
	/Users/ethan.brown/go/pkg/mod/github.com/danielgtaylor/huma/v2@v2.3.0/schema.go:351 +0x390
github.com/danielgtaylor/huma/v2.SchemaFromType({0x1033801a0, 0x14000274540}, {0x103386ec8, 0x103358720})
	/Users/ethan.brown/go/pkg/mod/github.com/danielgtaylor/huma/v2@v2.3.0/schema.go:557 +0xb00
github.com/danielgtaylor/huma/v2.(*mapRegistry).Schema(0x14000274540, {0x103386ec8, 0x103358720}, 0x1, {0x140001ec820, 0x1b})
	/Users/ethan.brown/go/pkg/mod/github.com/danielgtaylor/huma/v2@v2.3.0/registry.go:103 +0x228
github.com/danielgtaylor/huma/v2.SchemaFromField({0x1033801a0?, 0x14000274540?}, {{0x103284751, 0x4}, {0x0, 0x0}, {0x103386ec8, 0x103358720}, {0x0, 0x0}, ...}, ...)
	/Users/ethan.brown/go/pkg/mod/github.com/danielgtaylor/huma/v2@v2.3.0/schema.go:322 +0x80
github.com/danielgtaylor/huma/v2.Register[...]({_, _}, {{0x103199f7a, 0x4}, {0x1031a381d, 0x16}, 0x0, 0x0, 0x0, {0x0, ...}, ...}, ...)
	/Users/ethan.brown/go/pkg/mod/github.com/danielgtaylor/huma/v2@v2.3.0/huma.go:491 +0x2f8
github.com/train-artifact-index-service/internal/app/handler.ApiV1(0x1400029f948)
```

**Comment by danielgtaylor** [comment]
This is almost certainly because the Go implementation is a struct while the schema says it should be a string. The json field tag loader is assuming it should be an object, which in this case is a bug. I'll see what can be done to make this work as expected! Thanks for the bug report 👍🏻

**Comment by danielgtaylor** [comment]
@ddl-ebrown this should be fixed in `main` - mind giving it another try? The one caveat is that the `default` field tag will not work, but `example` and `enum` should now work well.

The `default` issue is a bigger one. If it's important to support I can dig deeper into it. The solution may be for types that provide a custom schema to also provide a method for assigning a default value, since we can't know how and where to assign the default from reflection alone.
