### ISSUE TITLE
`WriteErr()` does not respect HTTP status returned by `GetStatus()` of implemented `StatusError` interface

### ISSUE THREAD

**Issue by servernoj** [danielgtaylor/huma#232]
Hello,

My customized error response generated by the overridden `huma.NewError()` also handles input validation errors. It generates the correct response body, but the status is always (so far) 422, regardless of the value returned by the `GetStatus()` method of the `StatusError` returned from the overridden `huma.NewError()`. 

I suspect it happens because of how `WriteErr` finalizes and sends an error response
https://github.com/danielgtaylor/huma/blob/42461d5a01b508b5de841a93b056d0e8617f77d0/error.go#L209-L228

Specifically, the statement `ctx.SetStatus(status)` uses value of status passed to `WriteErr` instead of using result of `GetStatus` returned from `err` created as https://github.com/danielgtaylor/huma/blob/42461d5a01b508b5de841a93b056d0e8617f77d0/error.go#L210

I found a requirement in the definition of the `ErrorModel` type
https://github.com/danielgtaylor/huma/blob/42461d5a01b508b5de841a93b056d0e8617f77d0/error.go#L77-L80

But in cases of custom error responses like mine, I don't clearly see a rationale to ignore the value returned by `GetStatus()`

Thank you.

**Comment by servernoj** [comment]
Since I don't control where and how `WriteErr` is called, I guess my best options would be 
- to override the implementation of `WriteErr` to add extra logic for status value evaluation and call the original `WriteErr` with the needed status code
- follow the logic on how `WriteError` is invoked in the operation handler and inject some logic/fields into my custom error response struct to achieve the desired behavior (if possible)

**Comment by servernoj** [comment]
@danielgtaylor here is the overridden `NewError` that doesn't do much yet, but effectively tries to generate response body based on the "kind" of reported error:
```go
func (impl VersionedImpl) NewError(status int, message string, errs ...error) huma.StatusError {
	if status == http.StatusUnprocessableEntity && message == "validation failed" {
		return ErrorMap.GetErrorResponse(Err424_UnknownError)
	}
	return &api.ErrorResponse{
		Code:    status*api.ErrStatusGain + status,
		Message: message,
	}
}
```
the following line (appearing in the 1st return statement) is meant to "intercept" errors returned by the internal validation and report them in some specific way (to be defined later). I have not yet implemented the logic of that "specific way" but the idea is to analyze the slice of `errs` and call `ErrorMap.GetErrorResponse(...)` with the specific constant value.
```go
ErrorMap.GetErrorResponse(Err424_UnknownError)
```
the `Err424_UnknownError` is an `int` (field `Code` in the struct shown below) constant that is being looked up in a map by means of `ErrorMap.GetErrorResponse()` to find a matching descriptive text and produce/return an object of type
```go
type ErrorResponse struct {
	Status  int    `json:"-"`
	Code    int    `json:"code"`
	Message string `json:"message"`
}
```
with two methods allowing it to be treated as implementing `StatusError` interface
```go
func (er *ErrorResponse) GetStatus() int {
	if er.Status > 0 {
		return er.Status
	}
        // constand ErrStatusGain is equal to 10,000
	return er.Code / ErrStatusGain
}
func (er *ErrorResponse) Error() string {
	return er.Message
}
```
with `Code` field being defined as `ErrStatusGain * <some HTTP status> + <specific number for the error>`

For example, here I defined `Err424_UnknownError` as number `4241011` but left it without a matching text entry in the map -- it makes the implementation logic of the `ErrorMap.GetErrorResponse(Err424_UnknownError)` to return
```go
return &ErrorResponse{
	Status:  http.StatusInternalServerError,
	Code:    errorCode, // errorCode here is Err424_UnknownError
	Message: fmt.Sprintf("Unable to process unmapped error code %d", errorCode),
}
```
and so my expectation, since I return `ErrorResponse` with the defined `Status` field as `http.StatusInternalServerError` (or 500) would be to use it AS-IS in the defined `GetStatus()` (see above), and so to, set HTTP status as 500 but I'm getting 422 instead.

**Comment by servernoj** [comment]
I think I found a solution... I looked at what `WriteErr` does before sending out the response and noticed it passes the context via the sequence of registered transformers, so I added one during the config initialization:
```go
func(ctx huma.Context, status string, v any) (any, error) {
	if statusError, ok := v.(huma.StatusError); ok {
		// override response status to respect the status returned by NewError
		ctx.SetStatus(statusError.GetStatus())
	}
	return v, nil
}
```
seems to work as expected, and it overrides the returned status.

@danielgtaylor could there be any problems with that approach?

**Comment by danielgtaylor** [comment]
@servernoj I think a transformer can work and don't see any immediate problems with that.

That said, I'm still a little confused. Here's an example you can run showing:

1. Input validation error using a custom error
2. Input validation error using a resolver returning a custom error with custom HTTP status
3. Handler error with a custom HTTP status

https://go.dev/play/p/3bcwUMyQ5Hp

Hope that is helpful 😄

**Comment by servernoj** [comment]
@danielgtaylor thank you for elaborating this issue with great details.

My concern is about internal validation, i.e. the case shown below:
```
Error response http://example.com/greet/name_too_long:
Got HTTP 422
{
  "$schema": "https://example.com/schemas/ErrorResponse.json",
  "code": 123,
  "message": "validation failed\nexpected length \u003c= 10 (path.name: name_too_long)"
}
```
The `GreetingRequest` is defined to validate path param `name`
```go
type GreetingRequest struct {
	Name string `path:"name" maxLength:"10"`
}
```
but because of the way how you implemented `NewErrror()` and `ErrorResponse.GetStatus()`:
```go
huma.NewError = func(status int, msg string, errs ...error) huma.StatusError {
    for _, err := range errs {
        msg += "\n" + err.Error()
    }
    return &ErrorResponse{StatusCode: status, Code: 123, Message: msg}
}
func (e *ErrorResponse) GetStatus() int {
	return e.StatusCode
}
```
the returned HTTP status matches the one that was passed into `NewError`.

My use case requires (sometimes) to override that status in favor of returning something else. For example, if I define `NewError()` as
```go
huma.NewError = func(status int, msg string, errs ...error) huma.StatusError {
    for _, err := range errs {
        msg += "\n" + err.Error()
    }
    if status == 422 {
        status = 500
    }
    return &ErrorResponse{StatusCode: status, Code: 123, Message: msg}
}
```
the desired `500` will be ignored, and I will get 422.

PS: Have you had a chance to see/use https://goplay.tools/ -- a Better (how the devs call it) Go playground?

**Comment by servernoj** [comment]
Thank you, @danielgtaylor; I close this issue and will use the transformer-based approach.
