### ISSUE TITLE
`Resolve()` called twice

### ISSUE THREAD

**Issue by servernoj** [danielgtaylor/huma#234]
Hello,

I implemented `huma.Resolver` on the embeddable input struct
```go
type AuthorizationHeader struct {
	Authorization string `header:"authorization"`
}

func (ah *AuthorizationHeader) Resolve(ctx huma.Context) []error {
	log.Info().Msg(ah.Authorization)
	return nil
}
```
which is used to define the operation's input like this:
```go
type GetUserInput struct {
	AuthorizationHeader
}
```

When I make a request and pass the `Authorization` header, I see its value logged twice. Is this expected?

Thank you.

**Comment by danielgtaylor** [comment]
Confirmed, this is a bug. The parent struct gets the `Resolve` method from the included `AuthorizationHeader` so they wind up both getting called, which is really just calling the one method twice. See https://go.dev/play/p/Y8B71AljIdG.

This shouldn't hurt anything except performance, so you should still be able to continue on while it is fixed. Likely the `findResolvers` function needs to be rewritten to take this into account somehow.

**Comment by servernoj** [comment]
@danielgtaylor In the meantime, I added a boolean flag `Resolved` into `AuthorizationHeader`, and I check/set it in the resolver function to avoid any duplicated work.

Would you accept a PR if I find a way to fix it?
