### ISSUE TITLE
Setting Request Body to text/plain

### ISSUE THREAD

**Issue by Shackelford-Arden** [danielgtaylor/huma#249]
I'll state that I've had my eyes glued to the docs for a bit now and haven't found anything that either works as I intended or makes sense to lead me to a solution.

## Issue

I have an endpoint that needs to accept just a raw string, the application parses the string later.

Right now, I have the input Struct defined as:

```go

type RouteInput struct {
    Body string
}

```

Once the app is up and running however, the route still shows as only accepting `application/json` instead of `text/plain`. And, testing this out, I do indeed get a validation response indicating that `text/plain` is not expected/supported by the route.

### io.Reader

Other than the above noted struct, I've also attempted this struct:

```go

type RouteInput struct {
    Body io.Reader
}
```

And then read the string myself, however I end up in a similar boat w/ `application/json` being the expected Content-Type.

### Defining RequestBody

In reading through the docs and inspecting things a bit, I saw mention of defining `RequestBudy` when registering an operation. I defined that as such:

```go

    huma.Register(api, huma.Operation{
	OperationID: "the-bestest-route",
	Summary:     "The Bestest Route",
	Method:      http.MethodPost,
	Path:        "/api/v1/bestest-route",
	RequestBody: &huma.RequestBody{
	    Content: map[string]*huma.MediaType{
	        "text/plain": {
		    Encoding: map[string]*huma.Encoding{
		        "bar": {ContentType: "plaintext"},
		    },
		},
            },
	},
    },
    handlers.BestestRouteHandler,
    )

```

I used the above w/ both of the previously stated structs with the same results.

## Expected

I'd have hoped that by simply setting `Body` on `RouteInput` to a string, Huma would have picked up on that and appropriately adjusted the Content-Type. Or even just being able to override it w/ `RequestBody`, though that path is still a bit verbose (but I could live with it!).

**Comment by danielgtaylor** [comment]
@Shackelford-Arden here's an example of how you can accomplish this by using `RawBody []byte` and a `contentType` field tag instead of a `Body` field:

```go
// Register a simple hello world operation in the API.
huma.Register(api, huma.Operation{
	OperationID: "get-greeting",
	Method:      http.MethodPost,
	Path:        "/test",
}, func(ctx context.Context, input *struct {
	RawBody []byte `contentType:"text/plain"`
}) (*struct{}, error) {
	fmt.Println("You sent:", string(input.RawBody))
	return nil, nil
})
```

https://go.dev/play/p/YIjkdzyDe4_6

I'll look into the bug where it is replacing your schema and try to fix that ASAP. Oh and regarding `Body string`, this still triggers parsing & validation so it is seen as e.g. a JSON quoted string input. If you don't want structured data that gets parsed by Huma you probably want `RawBody` most of the time! I'll try to make that more clear in the docs.

**Comment by Shackelford-Arden** [comment]
Ahh ok! I see how this is documented here:

https://huma.rocks/features/request-inputs/#request-body

I think I'm tripped up a little by understanding the documenting of the `contentType:"text/plain"` in the struct. Definitely read this section a few times but didn't connect it back to being in the struct itself. 

That said, this does get me what I need :) Thank you!

**Comment by danielgtaylor** [comment]
I double checked whether setting a `RequestBody` explicitly still results in an `application/json` content type and can't seem to reproduce that issue. You do still get a validation error when using `Body`, but `RawBody` fixes that by bypassing the unmarshal & validate steps. I actually don't think there is a bug here, just that the documentation could be improved. Example at https://go.dev/play/p/YDAlWITnkn- shows the OpenAPI generates as:

```yaml
paths:
  /test:
    post:
      operationId: get-greeting
      requestBody:
        content:
          text/plain:
            encoding:
              bar:
                contentType: plaintext
```

It has the same OpenAPI output when using `Body`. So I'll try to update the docs and make this more clear!

**Comment by Shackelford-Arden** [comment]
Thank you @danielgtaylor ! Much appreciated :)
