### ISSUE TITLE
log error in middleware

### ISSUE THREAD

**Issue by jensravn** [danielgtaylor/huma#260]
If a handler returns an error would it be possible to make it available in the huma.Context to log it in the middleware. I was thinking something along these lines:

```go
api.UseMiddleware(func(ctx huma.Context, next func(huma.Context)) {
	next(ctx)
	err := ctx.Error()
	if err != nil {
		log.Default(err)
	}
})
```

**Comment by danielgtaylor** [comment]
@jensravn middleware works at a different layer than the operation handler return values, so it's not possible to access the `error` in the middleware. By the time the middleware runs the `error` has been turned into a status code, headers, body, etc. So today you have a few options:

1. Log error responses in middleware. You can wrap `ctx` with your own struct that implements `huma.Context` to record the response if the status code is >= 300 and log it.
2. You can try using a [Transformer](https://huma.rocks/features/response-transformers/) which runs after the operation handler function but *before* marshaling. Something like `if err, ok := v.(error); ok { ... log here ... }`.
3. You can wrap `huma.Register` to add additional error handling code after any operation runs. Take a look at #259 for an example of wrapping: https://go.dev/play/p/9rKBGZ45eBc.

Your suggestion of adding a `ctx.Error()` could work, but would require a new method in the `huma.Context` interface and storing the error in each adapter. Any reason you need it in the middleware instead of using the methods above?

**Comment by danielgtaylor** [comment]
I'm going to close this as answered, but please reopen if you still have questions!

**Comment by jensravn** [comment]
> @jensravn middleware works at a different layer than the operation handler return values, so it's not possible to access the `error` in the middleware. By the time the middleware runs the `error` has been turned into a status code, headers, body, etc. So today you have a few options:
> 
> 1. Log error responses in middleware. You can wrap `ctx` with your own struct that implements `huma.Context` to record the response if the status code is >= 300 and log it.
> 2. You can try using a [Transformer](https://huma.rocks/features/response-transformers/) which runs after the operation handler function but _before_ marshaling. Something like `if err, ok := v.(error); ok { ... log here ... }`.
> 3. You can wrap `huma.Register` to add additional error handling code after any operation runs. Take a look at [Implementing global error handler #259](https://github.com/danielgtaylor/huma/issues/259) for an example of wrapping: https://go.dev/play/p/9rKBGZ45eBc.
> 
> Your suggestion of adding a `ctx.Error()` could work, but would require a new method in the `huma.Context` interface and storing the error in each adapter. Any reason you need it in the middleware instead of using the methods above?

Thank you @danielgtaylor for the elaborate answer. I ended up with a combination of suggestion 1. and 3.
 - Wrapping `huma.Register` to log when a handler returns an error.
 - And wrapping `ctx` in middleware to store the trace id from the request header so I can put it on the log entry.

```go
type NewContext struct {
	humaCtx huma.Context
	newCtx  context.Context
}

// override Context() to return our new context
func (c *NewContext) Context() context.Context { return c.newCtx }

// delegate all other methods to the original huma.Context
func (c *NewContext) AppendHeader(name, value string)            { c.humaCtx.AppendHeader(name, value) }
func (c *NewContext) BodyReader() io.Reader                      { return c.humaCtx.BodyReader() }
func (c *NewContext) BodyWriter() io.Writer                      { return c.humaCtx.BodyWriter() }
func (c *NewContext) EachHeader(cb func(name, value string))     { c.humaCtx.EachHeader(cb) }
func (c *NewContext) GetMultipartForm() (*multipart.Form, error) { return c.humaCtx.GetMultipartForm() }
func (c *NewContext) Header(name string) string                  { return c.humaCtx.Header(name) }
func (c *NewContext) Host() string                               { return c.humaCtx.Host() }
func (c *NewContext) Method() string                             { return c.humaCtx.Method() }
func (c *NewContext) Operation() *huma.Operation                 { return c.humaCtx.Operation() }
func (c *NewContext) Param(name string) string                   { return c.humaCtx.Param(name) }
func (c *NewContext) Query(name string) string                   { return c.humaCtx.Query(name) }
func (c *NewContext) SetHeader(name, value string)               { c.humaCtx.SetHeader(name, value) }
func (c *NewContext) SetReadDeadline(t time.Time) error          { return c.humaCtx.SetReadDeadline(t) }
func (c *NewContext) SetStatus(code int)                         { c.humaCtx.SetStatus(code) }
func (c *NewContext) URL() url.URL                               { return c.humaCtx.URL() }

func TraceMiddleware(humaCtx huma.Context, next func(huma.Context)) {
	newCtx := &NewContext{
		humaCtx: humaCtx,
		newCtx: context.WithValue(humaCtx.Context(), "trace", humaCtx.Header("X-Cloud-Trace-Context")),
	}
	next(newCtx)
}

func Register[I, O any](api huma.API, op huma.Operation, handler func(context.Context, *I) (*O, error)) {
	huma.Register(api, op, func(ctx context.Context, input *I) (*O, error) {
		res, err := handler(ctx, input)
		if err != nil {
			trace := ctx.Value("trace").(string)
			logError(trace, err)
		}
		return res, err
	})
}
```
