### ISSUE TITLE
Best (safest) way to suppress logging in `humatest`

### ISSUE THREAD

**Issue by servernoj** [danielgtaylor/huma#262]
Hello,

I use `humatest` to run integration tests against all implemented Huma operations with multiple requests per operation. Every one of those requests logs "request" and "response" data, and in the case of verbose testing mode (CLI options `-v`), it makes it difficult to trace the console log for other information visually.

I noticed `humatest.New()`, when fed with `*testing.T`, uses it as an implementation of a subset of `testing.TB` interface, specifically for methods `Helper()`, `Log()` and `Logf()`.

I defined custom struct
```go
type MyTB struct {
	disableLogging bool
	*testing.T
}

func (tb *MyTB) Log(args ...any) {
	if !tb.disableLogging {
		tb.T.Log(args...)
	}
}
func (tb *MyTB) Logf(format string, args ...any) {
	if !tb.disableLogging {
		tb.T.Logf(format, args...)
	}
}
```
that is fed into `humatest.New()` in place of `*testing.T` like this
```go
// here `t` is `*testing.T`
myTB := &MyTB{
	T:              t,
	disableLogging: true,
}
_, api := humatest.New(myTB)
```
This approach allows me to control logging in `humatest` but I wanted to make sure it is safe to be used.

Thank you.

**Comment by danielgtaylor** [comment]
@servernoj I think that's fine. Also keep in mind you don't have to use `humatest`, it's just a convenience layer that does things like logging in the case of failures. It's perfectly fine to just use a `http.NewRequest()` and `httptest.NewRecorder()` along with the router's `ServeHTTP()` method, like https://pkg.go.dev/net/http/httptest#example-ResponseRecorder.
