### ISSUE TITLE
No test coverage when using `humatest`

### ISSUE THREAD

**Issue by servernoj** [danielgtaylor/huma#263]
Hello,

I have all my operations registered via `AutoRegister` [flow](https://pkg.go.dev/github.com/danielgtaylor/huma/v2#AutoRegister), and I adopted the same approach (by sniffing implementation of `huma.AutoRegister`) when registering operations against `humatest.TestAPI`. 

This approach works as expected, but `go test -cover` shows `coverage: [no statements]`. Is that behavior expected? 

PS: I was inspired by the [example](https://huma.rocks/tutorial/writing-tests/#writing-tests_1) that suggests the use of `go test -cover`... without showing the response :)

Thank you

**Comment by servernoj** [comment]
@danielgtaylor could it be because of how I register operations in front of testing API? As I mentioned, I do them all at once via reflection, and this is the only reason I can think of that may cause incorrect reporting. 

The example in question registers the operation more explicitly, i.e., via a direct call to `huma.Register`. I guess I need to try it out to see if it makes a difference.

**Comment by servernoj** [comment]
I was able to reproduce the problem on a smaller scale by moving operations into a separate package https://github.com/servernoj/huma-test

I now use `huma.AutoRegister` in both cases: in `main` and `main_test`.

Am I missing something obvious?

**Comment by danielgtaylor** [comment]
@servernoj I have to run to an appointment and then have a bunch of meetings, so don't have time to dig deep, however:

> shared code factored out into a separate module confuses the coverage calculation

That's likely the problem. Go coverage works only in the package with the tests, so each package is expected to have its own tests that cover the code in the package. If your tests are in `main` and covering stuff in `service`, it won't count that.

**Comment by servernoj** [comment]
that is likely the case, I tried moving things into the same package, and coverage started working https://github.com/servernoj/huma-test/tree/same-package

**Comment by servernoj** [comment]
@danielgtaylor I refactored my original application and started to see actual coverage. Thank you for pointing me in the right direction.
