### ISSUE TITLE
Customizable CLI name instead of `myapp`

### ISSUE THREAD

**Issue by xarunoba** [danielgtaylor/huma#264]
It would be nice to also set the command name instead of being locked to only `myapp` when creating a new CLI using `huma.NewCLI` instead of creating the CLI using Cobra directly.

What do you think? :)

**Comment by danielgtaylor** [comment]
@xarunoba thanks for pointing this out! It's possible today but not documented, since you have direct access to the root command:

```go
cli.Root().Use = "appname"
cli.Root().Version = "1.0.1"
```

I created #265 to set a better default and document how to manually set these things, let me know what you think!

**Comment by xarunoba** [comment]
Sounds good to me! Thanks for the quick reply!
