### ISSUE TITLE
Custom validation struct tag

### ISSUE THREAD

**Issue by victoraugustolls** [danielgtaylor/huma#267]
Hi! First of all, thanks for the fantastic work! I missed something like `FastAPI` when I transitioned to Go, and I'm testing Huma now. So far, it is great!!

I wondered if there is a way to register custom validators as struct tags. I have a use case where I want my fields (3 strings) of the body to be non-whitespace strings. I tried using the regex `^\S*` for this, but unfortunately, when using this regex inside the struct tag, it gives an error for me.

I could use resolvers, but it seems that I would be repeating myself too much in this case! Any ideas?

Thanks in advance!!

**Comment by victoraugustolls** [comment]
@servernoj, the `pattern` tag works, but not for my case! The problem is due to the go string nature since it considers a `\S` an invalid escape sequence inside a double quotes string :/.

**Comment by servernoj** [comment]
did you try `\\S` instead?

**Comment by victoraugustolls** [comment]
Yes I did try this way an know that it works! The problem in this case is the error message:

`"message": "expected string to match pattern ^\\S+$"`

I'm afraid that a user can interpret this as a different pattern than it is supposed to. The same is true for the docs rendered.

**Comment by victoraugustolls** [comment]
@danielgtaylor I was sure that when I did custom resolvers, I saw a single `\` in the error message. Trying it again now, it did not. I guess working at 3 am is not ideal :/. I'm sorry for the confusion!
