### ISSUE TITLE
Handler Type

### ISSUE THREAD

**Issue by victoraugustolls** [danielgtaylor/huma#268]
Would you be open to a PR creating a `Handler` type with the following structure?

`type Handler[I, O any] func (context.Context, *I) (*O, error)`

I created it internally in my project to make transitioning easier than writing the signature every time, and it might help others! If you are open to it, I can open a PR!

**Comment by danielgtaylor** [comment]
@victoraugustolls how are you using this type in your code? I wouldn't mind adding it but there's one place I don't want to change: `huma.Register`. I think it provides more info to the user in editors/IDEs on hover or jump to definition by keeping the full function definition over hiding it behind a type:

<p align="center">
<img width="503" alt="Screenshot 2024-02-28 at 22 26 10" src="https://github.com/danielgtaylor/huma/assets/106826/d723783f-5d18-4357-9c5f-98347ac4d9a9">
</p>

**Comment by danielgtaylor** [comment]
I believe this was answered, so let me know if you have any other questions!
