### ISSUE TITLE
Mocking resolvers

### ISSUE THREAD

**Issue by servernoj** [danielgtaylor/huma#269]
Hello,

I have an embeddable resolver that makes an HTTP request to set the custom field. Here are the types definitions for a hypothetical `Get` operation:
```go
type MyInput struct {
	MyResolver	
}

type MyResolver struct {
	MyHeader     string `header:"my-header"`
	FieldToBeSet string
}

func (input *MyResolver) Resolve(ctx huma.Context) []error {
	// 1. Make an HTTP request to process `input.MyHeader`
	// 2. Set `input.FieldToBeSet` with the value based on the response
	// 3. Handle and return possible errors
	return nil
}
```

For the purpose of integration testing, I want to mock that HTTP request, but I cannot figure out how and where to pass a mocked implementation of `MyResolver`.

I think it is too late to do it when the registered handler (the one that takes context and input and returns output and error) kicks in because, at that time, the resolver has already been invoked. 

A possible solution would be to have a hook (of some sort) executed by Huma before it instantiates and fills in the input structure.

Thank you.

**Comment by danielgtaylor** [comment]
@servernoj you might be trying to do too many things in a resolver to be honest. Making full HTTP requests might be better to put into the operation handler (which can still call some utility function to make the requests) and then you can create the handler by passing it a mocked HTTP client.

Another option is to mock out the default client in tests using something like https://github.com/h2non/gock which I've used and works well. The rest of the code thinks it is making real requests so nothing needs to change in the resolver.

Lastly, you could write a small middleware that inserts an HTTP client into the request context, and then pull that out in your resolver before making the request. This complicates your production code though so is probably not recommended.

**Comment by servernoj** [comment]
@danielgtaylor I use that HTTP request to validate and parse a JWT token sent in the authorization header. The resolver would set the `userId` field if the token is valid and the associated user is found in DB. I then embed that struct into input types of all operations meant to receive that authorization header. It worked well (from a convenience standpoint), but now it troubles me. 

I am halfway to implementing that approach with middleware, but instead of injecting the HTTP client into `Context`, I went to inject the entire resolver. I planned it to be extracted and used by the actual resolver to perform the task. This solution becomes overcomplicated, and I guess I will not continue this way.

I am trying to stay away from using package-level variables to pass in dependencies but at the same time, I need something to be on/off configurable on a per-operation basis. 

Thank you for the suggestion to try https://github.com/h2non/gock and a way to wrap the operation handler so it could receive a mocked HTTP client. 

I will try those few things and will post here my findings (for possible review by others) before closing the ticket.

Thank you.

**Comment by servernoj** [comment]
I ended up using the `gock` library. 

I'm a little hesitant to continue using a "loaded" resolver that makes HTTP requests, but the needed effort of refactoring all operations from "one line setup" to "injecting and using non-default HTTP client" makes me stay with the current implementation. 

Thank you.
