### ISSUE TITLE
Default HTML title of Docs

### ISSUE THREAD

**Issue by elmarw** [danielgtaylor/huma#273]
How to change the default title of the html generate docs on /docs?

The default title seems to be Stoplight's "Elements in HTML".

**Comment by danielgtaylor** [comment]
@elmarw the docs are set up here by default but can be disabled for customization:

https://github.com/danielgtaylor/huma/blob/main/api.go#L355-L386

You can just set `config.DocsPath = ""` and then add your own handler using whatever docs settings or tools you like:

```go
config := huma.DefaultConfig("My API", "1.0.0")
config.DocsPath = ""

api := humachi.New(router, config)
api.Adapter().Handle(&Operation{
	Method: http.MethodGet,
	Path:   config.DocsPath,
}, func(ctx Context) {
	ctx.SetHeader("Content-Type", "text/html")
	ctx.BodyWriter().Write([]byte(`whatever you want here!`))
})
```

You can just copy the default and modify the title, or use something entirely different like [SwaggerUI](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/installation.md#unpkg) or [Scalar Docs](https://github.com/scalar/scalar?tab=readme-ov-file#from-a-cdn). It's up to you!

**Comment by danielgtaylor** [comment]
@elmarw hopefully this answers the question. If not, feel free to re-open the issue!
