### ISSUE TITLE
How do I display endpoint query params in the OpenAPI docs site?

### ISSUE THREAD

**Issue by bclements** [danielgtaylor/huma#277]
I have a chi router middleware called pagination which works pretty well and I can paginate easily using ```/stuff?page=X&size=Y```

Only problem is that when I go to /docs, I don't see the query params page and size displayed the stoplight docs....how can I get them to display?

Here is a snippet of my huma main.go file.

```
		router := chi.NewMux()
		router.Use(middleware.RequestID)
		router.Use(middleware.Logger)
		router.Use(middleware.Recoverer)
		router.Use(render.SetContentType(render.ContentTypeJSON))
		router.Use(DBSessionMiddleware(dbPool))
		router.Use(pagination.Paginate)

		api := humachi.New(router, config)

		huma.Register(api, huma.Operation{
			OperationID: "get-stuff",
			Summary:     "Gets all stuff",
			Method:      http.MethodGet,
			Path:        "/stuff",
		}, handlers.GetAllStuff)
```

I appreciate any help. Also, I'm happy to donate or pay for a "coffee" to thank you for the awesome framework!!

**Comment by bclements** [comment]
I found my own answer. Basically you have to supply Parameters field to the Operation declaration, ie, right after Path: "/stuff", 

I added 

```
			Parameters: []*huma.Param{
				{
					Name:        "page",
					In:          "query",
					Description: "The page number to retrieve",
					Required:    false,
				},
				{
					Name:        "size",
					In:          "query",
					Description: "The number of items per page",
					Required:    false,
				},
			},
```

**Comment by danielgtaylor** [comment]
@bclements yep, and if this is something you need to do more often you can create a small utility function that takes a `huma.Operation` and returns it with those params added, so you can do something like:

```go
huma.Register(api, WithPagination(huma.Operation{
  // ...
}), handler)
```

It's set up to be relatively easy to wrap and augment as needed.
