### ISSUE TITLE
Form Data in POST Body

### ISSUE THREAD

**Issue by thulasidhar** [danielgtaylor/huma#285]
Hi,

First of all thanks for the wonderful framework you have designed and developed... this has certainly made my golang webapi development much more structured and maintainable.

I have a specific question wrt handling form data (application/x-www-form-urlencoded) and I couldnt find any example in handling this body type. Is there a recommended way of handling form body data in huma?

**Comment by Insei** [comment]
Hi! You need write a [resolver](https://huma.rocks/features/request-resolvers/?h=resol) for you input struct, and in huma.Context we have GetMultipartForm func, where you can get form and work with it as usually

**Comment by thulasidhar** [comment]
Thanks for the pointer @Insei 
The GetMultipartForm func seems to accept only multipart/form-data

I managed to write a generic resolver to Unmarshal into my struct

```
func (m *ActionForm) Resolve(ctx huma.Context) []error {
	limitedReader := &io.LimitedReader{R: ctx.BodyReader(), N: 4096}
	body, err := io.ReadAll(limitedReader)

	err = urlquery.Unmarshal(body, m)
	if err != nil {
		return []error{err}
	}

	return nil
}
```

but I'm getting this error now
```
{
    "$schema": "http://localhost:8081/schemas/ErrorModel.json",
    "title": "Unsupported Media Type",
    "status": 415,
    "detail": "validation failed",
    "errors": [
        {
            "message": "unknown content type: application/x-www-form-urlencoded",
            "location": "body",
            "value": "aHR0cDovL2xvY2FsaG9zdDo4MDgxL3NjaGVtYXMvRXJyb3JNb2RlbC5qc29uVXJsPWh0dHBzJTNBJTJGJTJGZ29vZ2xlLmNvbQ=="
        }
    ]
}
```

I added the contentType to the input struct
```
func (s *authAPI) action(ctx context.Context, input *struct {
	Type   string     `path:"type" example:"google"`
	Action string     `path:"action" example:"login|callback"`
	State  string     `query:"state"`
	Code   string     `query:"code"`
	Body   ActionForm `contentType:"application/x-www-form-urlencoded"`
}) (*response, error) {
```
but still see the same error

**Comment by Insei** [comment]
Oh, yeah, sorry, with url encoded it seems can't work, another solution: use [raw body](https://huma.rocks/features/request-inputs/?h=raw#other-body-types) input struct field, and parse data manually

**Comment by danielgtaylor** [comment]
@thulasidhar keep in mind that if you have one specific HTTP call that Huma isn't a great fit for, you don't have to use Huma for it. You can just use the underlying router directly and get full access to the incoming request for special cases. That also makes it easy to serve static content and other use-cases without having to go through the Huma layer.

That said, if someone wants to add support for unmarshaling form data into input structs, I'd be open to reviewing/merging a PR for that. Just don't want to add many (or any) new dependencies if we can avoid it.

I also wonder if you can write a [`huma.Format`](https://pkg.go.dev/github.com/danielgtaylor/huma/v2#Format) to unmarshal form or url data, and put that into your [`huma.Config`](https://pkg.go.dev/github.com/danielgtaylor/huma/v2#Config) under `Formats` and have it mostly just work. I haven't tried it but it's worth an experiement.

**Comment by danielgtaylor** [comment]
I believe the question was answered, but feel free to re-open if you want to revisit it. Thanks!

**Comment by robertdodd** [comment]
Here is an example of accepting both `application/json` or `application/x-www-form-urlencoded`. It uses `gorilla/schema` for parsing urlencoded into structs via a `huma.Format`.

Validation works in this example, but won't work with complicated payloads -- see the notes in the decoder, where it parses it to a `map[string]any` first. Or, use `SkipValidation` and perform your own.

```go
package main

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/danielgtaylor/huma/v2"
	"github.com/danielgtaylor/huma/v2/adapters/humachi"
	"github.com/go-chi/chi/v5"
	"github.com/gorilla/schema"
)

type LoginRequest struct {
	Username string `schema:"username" json:"username" minLength:"1"`
	Password string `schema:"password" json:"password" minLength:"1"`
}

type LoginOutput struct {
	Body struct {
		Message string `json:"message"`
	}
}

// Set a Decoder instance as a package global, because it caches
// meta-data about structs, and an instance can be shared safely.
var decoder = schema.NewDecoder()

var urlEncodedFormat = huma.Format{
	Marshal: nil,
	Unmarshal: func(data []byte, v any) error {
		values, err := url.ParseQuery(string(data))
		if err != nil {
			return err
		}

                // WARNING: Dirty workaround!
		// During validation, Huma first parses the body into []any, map[string]any or equivalent for easy validation,
		// before parsing it into the target struct.
		// However, gorilla/schema requires a struct for decoding, so we need to map `url.Values` to a
		// `map[string]any` if this happens.
		// See: https://github.com/danielgtaylor/huma/blob/main/huma.go#L1264
		if vPtr, ok := v.(*interface{}); ok {
			m := map[string]any{}
			for k, v := range values {
				if len(v) > 1 {
					m[k] = v
				} else if len(v) == 1 {
					m[k] = v[0]
				}
			}
			*vPtr = m
			return nil
		}

		// `v` is a struct, try decode normally
		return decoder.Decode(v, values)
	},
}

func init() {
	// Add the x-www-form-urlencoded format to Huma.
	// This is how Huma's COBR package does it, but you could also update your `huma.Config` in `main`, like so:
	//
	//	config := huma.DefaultConfig()
	//	config.Formats["application/x-www-form-urlencoded"] = urlEncodedFormat
	//	config.Formats["x-www-form-urlencoded"] = urlEncodedFormat
	huma.DefaultFormats["application/x-www-form-urlencoded"] = urlEncodedFormat
	huma.DefaultFormats["x-www-form-urlencoded"] = urlEncodedFormat
}

func main() {
	router := chi.NewMux()

	config := huma.DefaultConfig("My API", "1.0.0")
	api := humachi.New(router, config)

	// Register the routers
	huma.Register(api, huma.Operation{
		OperationID: "login",
		Method:      http.MethodPost,
		Path:        "/token",
	}, func(ctx context.Context, input *struct {
		Body LoginRequest
	}) (*LoginOutput, error) {
		resp := &LoginOutput{}
		resp.Body.Message = fmt.Sprintf("%s signed in with %s", input.Body.Username, input.Body.Password)
		return resp, nil
	})

	// Start the server!
	err := http.ListenAndServe("127.0.0.1:8080", router)
	if err != nil {
		panic(err)
	}
}
```

**Open API Schema**

At this point it works, and you can test it with a `curl` request, but the Open API schema still only says JSON, so you can't test the new format from the docs page.

You can *almost* fix it with the below changes:

```go
// ONLY REQUIRED TO PATCH OPENAPI SCHEMA. It will work without this.
registry := api.OpenAPI().Components.Schemas
schema := registry.Schema(reflect.TypeOf(LoginRequest{}), true, "")

// Register the routers
huma.Register(api, huma.Operation{
	OperationID: "login",
	Method:      http.MethodPost,
	Path:        "/token",
	// ONLY REQUIRED TO PATCH OPENAPI SCHEMA. It will work without this.
	RequestBody: &huma.RequestBody{
		Description: "Login Request",
		Content: map[string]*huma.MediaType{
			"application/x-www-form-urlencoded": {
				Schema: schema,
			},
			"application/json": {
				Schema: schema,
			},
		},
	},
}, func(ctx context.Context, input *struct {
	Body LoginRequest
}) (*LoginOutput, error) {
	resp := &LoginOutput{}
	resp.Body.Message = fmt.Sprintf("%s signed in with %s", input.Body.Username, input.Body.Password)
	return resp, nil
})
```

Now it shows both formats on the docs page, but unfortunately it includes the `$schema` property in the request.

I'm not sure how to get around this besides overriding the schema in `RequestBody`.

![Screenshot from 2024-11-01 10-21-07](https://github.com/user-attachments/assets/7df9368b-3b8f-4e79-9744-26dfeee0ba4a)
