### ISSUE TITLE
unsupported param type panic when using a struct as a query param

### ISSUE THREAD

**Issue by bekabaz** [danielgtaylor/huma#288]
Running on v2.7.0

I have a need to use a struct for optional filters on a GET request. The struct is defined as follows:

> type FilterOpts struct {
> 	FilterId *int64  `json:"filter_id,omitempty" query:"filter_id"`
> 	Query    *string `json:"query,omitempty" query:"query"`
> }

When I register the route, I have a field defined as such to include the above struct:

> Filter FilterOpts `json:"filter,omitempty" query:"filter" maxProperties:"1"`

but this causes a panic with message: 

> unsupported param type controllers.FilterOpts

Context: I want to only allow the usage of 1 of those options at a time. Meaning,  a request can't have both a filter id and a query at the same time.  maxProperties seems like a good fit for the requirements. Is there any other way to achieve this?

edit: Seems like OpenAPI supports this https://swagger.io/docs/specification/serialization/

**Comment by danielgtaylor** [comment]
@bekabaz you might be able to make this work with a struct, but Huma doesn't support all of the possible serialization options out of the box that OpenAPI supports, both in an effort to keep things simple and keep the codebase a little cleaner. I would suggest using a resolver if you want one-of semantics for input parameters:

```go
type FilterOrQuery struct {
	FilterID int64  `query:"filter_id" doc:"filter_id and query are mutually exclusive"`
	Query    string `query:"query" doc:"filter_id and query are mutually exclusive"`
}

func (f *FilterOrQuery) Resolve(ctx huma.Context) []error {
	if f.FilterID != 0 && f.Query != "" {
		return []error{&huma.ErrorDetail{
			Message:  "Cannot pass both filter_id and query at the same time",
			Location: "query",
			Value:    fmt.Sprintf("filter_id:%d query:%s", f.FilterID, f.Query),
		}}
	}
	return nil
}
```

Then you can use it in the handler like this:

```go
huma.Get(api, "/demo", func(ctx context.Context, input *struct {
	FilterOrQuery
}) (*struct{}, error) {
	fmt.Printf("Got filter_id:%d query:%s\n", input.FilterID, input.Query)
	return nil, nil
})
```

Doing a `GET` on `/demo?filter_id=123` works, `/demo?query=foo` works, but `/demo?filter_id=123&query=foo` will return an error response.

Runnable code sample: https://go.dev/play/p/0GXKvASo8eZ

<details><summary>Click to expand full code example</summary>
<p>

```go
package main

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"

	"github.com/danielgtaylor/huma/v2"
	"github.com/danielgtaylor/huma/v2/adapters/humago"
)

type FilterOrQuery struct {
	FilterID int64  `query:"filter_id"`
	Query    string `query:"query"`
}

func (f *FilterOrQuery) Resolve(ctx huma.Context) []error {
	if f.FilterID != 0 && f.Query != "" {
		return []error{&huma.ErrorDetail{
			Message:  "Cannot pass both filter_id and query at the same time",
			Location: "query",
			Value:    fmt.Sprintf("filter_id:%d query:%s", f.FilterID, f.Query),
		}}
	}
	return nil
}

func main() {
	// Create a new stdlib HTTP router.
	mux := http.NewServeMux()

	// Create a Huma v2 API on top of the router.
	api := humago.New(mux, huma.DefaultConfig("Greet API", "1.0.0"))

	// Register a simple hello world operation in the API.
	huma.Get(api, "/demo", func(ctx context.Context, input *struct {
		FilterOrQuery
	}) (*struct{}, error) {
		fmt.Printf("Got filter_id:%d query:%s\n", input.FilterID, input.Query)
		return nil, nil
	})

	var out bytes.Buffer

	// Make a test request and print the response body.
	fmt.Println("Successful response:")
	req, _ := http.NewRequest(http.MethodGet, "/demo?filter_id=123", nil)
	req.Host = "example.com"
	w := httptest.NewRecorder()
	mux.ServeHTTP(w, req)
	json.Indent(&out, w.Body.Bytes(), "", "  ")
	out.WriteTo(os.Stdout)

	// Error example
	fmt.Println("\nError response:")
	req, _ = http.NewRequest(http.MethodGet, "/demo?filter_id=123&query=foo", nil)
	req.Host = "example.com"
	w = httptest.NewRecorder()
	mux.ServeHTTP(w, req)
	out.Reset()
	json.Indent(&out, w.Body.Bytes(), "", "  ")
	out.WriteTo(os.Stdout)
}

```

</p>
</details>

**Comment by bekabaz** [comment]
I'm good with that then, I already have validation for it, so nothing is broken. Thanks for the feedback!
