### ISSUE TITLE
API Gateway path issue?

### ISSUE THREAD

**Issue by bclements** [danielgtaylor/huma#297]
This may be a user error on my part so please bear with me.  BTW HUMA ROCKS!!

We are using AWS api gateway that points to our chi service.

apigw.domain.com/blogs -> blogs.domain.com

When we go to any endpoint hosted by our service using the apigw, example apigw.domain.com/blogs/new we get a not found error and the path dev tools says can be found is apigw.domain.com/new ....Looks ilke the chi router is not respecting the original path.

Is there a way to configure chi or huma to respect the path used by the apigw?

Also when I go to apigw.domain.com/blogs/docs the spotlight page tries to come up but getting a 404 complaining about not being able to reach apigw.domain.com/openapi.yaml.   

Any  advice or a hint  about where to start looking?

**Comment by Insei** [comment]
@bclements Hi! I not use the gateway, but use nginx ingress in k8s, in your situation, `rewrite` would help in order to add or trim unnecessary parts from the path.

And for advanced info can you share chi logs?

**Comment by Insei** [comment]
> apigw.domain.com/openapi.yaml

But with this file, situation is more complicated, because this path is hard coded in index.html, and the requests come from web browser(from client side).
@danielgtaylor Hi! Any ideas? Can we make path to the openapi.yaml relative in index.html?

**Comment by x-user** [comment]
> > apigw.domain.com/openapi.yaml
> 
> But with this file, situation is more complicated, because this path is hard coded in index.html, and the requests come from web browser(from client side). @danielgtaylor Hi! Any ideas? Can we make path to the openapi.yaml relative in index.html?

You can workaround this by using custom docs, see: [273](https://github.com/danielgtaylor/huma/issues/273#issuecomment-1973618623)

**Comment by bclements** [comment]
Thanks everyone but I don't think this solves my problem.

**Comment by danielgtaylor** [comment]
@bclements for the docs/openapi you should be able to set the `config.DocsPath`, `config.OpenAPIPath`, and `config.SchemasPath` to point to whatever directory you need. https://pkg.go.dev/github.com/danielgtaylor/huma/v2#Config

I'm not sure how you need to configure the API Gateway, but a chi middleware could be used to rewrite paths or you can include the `/blog` prefix in your registered operation paths.

**Comment by bclements** [comment]
The original workaround, which was to copy and paste the stoplight html into a custom handler worked perfectly. 

Closing the ticket.
