### ISSUE TITLE
Is there support for interface{} in the input body?

### ISSUE THREAD

**Issue by bekabaz** [danielgtaylor/huma#300]
I have an API method with a field in the request body that is an interface and 2 different structs that satisfy the interface. Is there support to document this properly in the OpenAPI output? I see the example for responses here: https://github.com/danielgtaylor/huma/blob/main/examples/oneof-response/main.go - is there anything similar for requests?

**Comment by bekabaz** [comment]
To add further info, I managed to get this working with manually specifying the RequestBody like this:

```
RequestBody: &huma.RequestBody{
	Description: "My custom request schema",
	Content: map[string]*huma.MediaType{
		"application/json": {
			Schema: &huma.Schema{
				OneOf: []*huma.Schema{
					registry.Schema(reflect.TypeOf(ProfileA{}), true, "ProfileA"),
					registry.Schema(reflect.TypeOf(ProfileB{}), true, "ProfileB"),
				},
			},
		},
	},
},
```

If this is the best way, I think this is acceptable for my requirements. One issue that I can see is on the generated docs, the drop down for the Body object has unlabeled items. Simply says "object" and "object". Is there a way to name those options? I thought the hint field on r.Schema() would do it, but doesn't seem so.

**Comment by danielgtaylor** [comment]
@bekabaz this isn't currently supported for inputs in any automated way, since Huma won't know how to discriminate between the two types to load. You can use a custom schema with `oneOf` and then accept a raw `[]byte` body which you have to parse yourself to figure out which type it should be, which can be done in various ways.

**Comment by bekabaz** [comment]
Thank you, see the update above if you don't mind. Got it working, but there is a detail in the docs that's an issue.

**Comment by bekabaz** [comment]
I looked at some other companies OpenAPI docs, and I wasn't able to find an example where the drop down items were labelled, so this may be a Stoplight thing. Thanks for the response @danielgtaylor
