### ISSUE TITLE
Access to all headers like `request.Header`

### ISSUE THREAD

**Issue by victoraugustolls** [danielgtaylor/huma#302]
I was developing an OpenTelemetry Tracer middleware for `Huma`, but when I tried propagating the headers, I noticed that I couldn't access all the headers at once to pass to the propagator. I ended up developing a native `chi` middleware instead.

The final result is:

```go
// TracingMiddleware extracts the headers from the request and starts the span.
func TracingMiddleware() func(next http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			ctx := otel.GetTextMapPropagator().Extract(r.Context(), propagation.HeaderCarrier(r.Header))
			ctx, span := StartSpan(ctx, r.Method)
			r = r.WithContext(ctx)

			defer span.End()

			next.ServeHTTP(w, r)

			span.SetName(fmt.Sprintf("%s %s", r.Method, chi.RouteContext(ctx).RoutePattern()))
		})
	}
}
```

I could implement a custom OTel Propagator for `Huma` to have a router-agnostic middleware, but I wanted your opinion here. My final goal is to provide ready-to-use router-agnostic middleware for `Huma` instrumentation. Do you think `Huma` should give access to the headers like the example above, or should I create a custom propagator for `Huma`? I'm okay with either solution.

**Comment by victoraugustolls** [comment]
That's perfect!  So I will create a custom propagator for Otel. When I finish my middlewares for OpenTelemetry, would you mind if I contributed them to the [official contribution repository](https://github.com/open-telemetry/opentelemetry-go-contrib)? If you prefer, I can put them somewhere else, maybe even in the `Huma` repository.

**Comment by victoraugustolls** [comment]
@danielgtaylor, when writing the agnostic middleware, I noticed that the user could not access the response code after calling `next(ctx)` in the middleware. Is this by design? Or could we include access to the status code?

**Comment by danielgtaylor** [comment]
@victoraugustolls feel free to submit it to the contrib repo, that would be great! As for accessing the response code, you will want to wrap the context with your own implementation that stores the status, something like:

```go
type MyContext struct {
  huma.Context
  status int
}

func (c *MyContext) SetStatus(code int) {
  c.status = code
  c.Context.SetStatus(code)
}
```

Then use that to wrap the incoming context, call `next(wrapped)` and then access `wrapped.status` when submitting metrics.

**Comment by victoraugustolls** [comment]
Thanks, @danielgtaylor! I will close this issue and let you know when I open a PR for the contrib repository.
