### ISSUE TITLE
Custom resolver for multipart form file upload 

### ISSUE THREAD

**Issue by ant1g** [danielgtaylor/huma#311]
Hello,

I have been experimenting with Huma and tried to implement a proper multipart form based file upload.
I am doing the following:

```golang
func (uf *FileUploadForm) Resolve(ctx huma.Context) []error {
	form, err := ctx.GetMultipartForm()
	if err != nil {
		return []errors{errors.Wrap(err, "get multipart form")}
	}

        // process form, copy file bytes to destination
}
```

The issue is that I want to pass dynamic configuration data to the resolver, for example: a destination directory where to copy the uploaded files.

AFAIK, the struct `FileUploadForm` that implement the interface is created by huma at the moment of parsing the request and calling my handler.

How can I pass it a config value without having to resort to global variables?

Thanks

**Comment by danielgtaylor** [comment]
@ant1g good question. I don't think it's really possible right now to instantiate it with any sort of inputs not coming from the request itself. One thing you could consider is passing it in via the context using a custom middleware, something like:

```go
api.UseMiddleware(func(ctx huma.Context, next func(huma.Context)) {
	ctx = huma.WithValue(ctx, "multipart-dir", "/tmp")
	next(ctx)
})
```

Then later use something like `val := ctx.Context().Value("multipart-dir").(string)` in the resolver. This has the benefit of not being a global var and you can set it from the app config (CLI options / env vars) as needed. Additionally you could change the location based on parameters in the request, e.g. by user account or across multiple disks in a non-RAID configuration. Hope this helps!

**Comment by jamelt** [comment]
I'm working on an update to Huma to support the multipart form. Would love to hear your thoughts on this API proposal?

```
huma.Register(api, huma.Operation{
	OperationID: "upload files",
	Method:      http.MethodPost,
	Path:        "/upload",
	Summary:     "Example to upload files",
}, func(ctx context.Context, input struct {
	RawBody *multipart.Form `contentType:"multipart/form-data"`
}) (*struct{}, error) {
	fmt.Println("Got input")
	return nil, nil
}
```

Although the content type could be inferred here.

You could then iterate over all the files in the RawBody. Would need to update the code to resolve that information

**Comment by danielgtaylor** [comment]
@jamelt that looks great, thanks! Personally I like the inferred content type with the ability to override.

**Comment by jamelt** [comment]
I put in a simple implementation. It's not the best code, but looks like it passes the unit tests. I'm going to try integrating it into my app really quick to see how it does. 

Here is a link to the commit. I'd be grateful for any feedback so I can get it up to the project's standards.

https://github.com/jamelt/huma/commit/cfa7accde3df67d489581d59872656e0201a98e7

**Comment by ant1g** [comment]
Thanks @danielgtaylor, I ended up using the request context to pass dynamic configuration data around.
