### ISSUE TITLE
Nested structs visibility not working properly

### ISSUE THREAD

**Issue by CptKirk** [danielgtaylor/huma#313]
It seems that visibility struct tags like `readOnly` and `writeOnly` are not applied to nested structs. To help understanding the problem I created a small example test in `huma_test.go` in function `TestFeatures`:
```go
{
	Name: "request-body-nested-struct-readOnly",
	Register: func(t *testing.T, api huma.API) {
		type NestedStruct struct {
			Foo struct {
				Bar string `json:"bar"`
			} `json:"foo" readOnly:"true"`
			Value string `json:"value"`
		}
		huma.Register(api, huma.Operation{
			Method: http.MethodPost,
			Path:   "/body",
		}, func(ctx context.Context, input *struct {
			Body *NestedStruct
		}) (*struct{}, error) {
			assert.Equal(t, true, true)
			return nil, nil
		})
	},
	Method: http.MethodPost,
	URL:    "/body",
	Body:   `{"value":"test"}`,
},
```

I expect the test to pass but it fails due to this error:
```json
{
  "$schema":"https:///schemas/ErrorModel.json",
  "title":"Unprocessable Entity",
  "status":422,
  "detail":"validation failed",
  "errors":[
    {
      "message":"expected required property foo to be present",
      "location":"body",
      "value":{"value":"test"}
    }
  ]
}
```
It says that property `foo` is required but it is set to `readOnly="true"` so this error is not correct.

I also noticed, that the `writeOnly` struct tag does not work as I expect it to. I thought that that the `writeOnly` tag would remove the corresponding fields from the response, but they are still sent in the response, is this expected behavior?

**Comment by victoraugustolls** [comment]
>  I thought that that the writeOnly tag would remove the corresponding fields from the response, but they are still sent in the response, is this expected behavior?

It might not be the same thing, but `writeOnly` is only set in the request; I don't think it would impact the response (at least, I wouldn't expect it to).

**Comment by bekabaz** [comment]
I have an issue that is related to this, and when I use the most up to date main, it is still present. The only difference in mine, is that it is saying a property is required, but it is not.

I have this as my input for the Operation:

```
Body struct {
	CreateSeq
}
```
and CreateSeq is defined as:
```
type CreateSeq struct {
	Ci *CI `json:"ci"`
	Name          string         `json:"name" required:"true"`
	Status        string         `json:"status" enum:"active,inactive" default:"inactive"`
}
```

This is the error I get on a request:
```
...
"message": "expected required property ci to be present",
"location": "body",
...
```

**Comment by bekabaz** [comment]
Forgot to tag you @danielgtaylor

**Comment by danielgtaylor** [comment]
@bekabaz because it's a part of the body, fields are required by default. Use Go's built-in `omitempty` feature to make them optional:

```go
Ci *CI `json:"ci,omitempty"`
```

This also means the `required:"true"` isn't necessary in your example.

**Comment by bekabaz** [comment]
> @bekabaz because it's a part of the body, fields are required by default. Use Go's built-in `omitempty` feature to make them optional:
> 
> ```go
> Ci *CI `json:"ci,omitempty"`
> ```
> 
> This also means the `required:"true"` isn't necessary in your example.

Thank you, don't know how I missed that, but glad I didn't clog you up with a new issue.
