### ISSUE TITLE
How can I sponsor the project?

### ISSUE THREAD

**Issue by bclements** [danielgtaylor/huma#316]
Hi, I'd love to throw some cash your way as a way to thank you for such a great framework and to keep this project going.  Anyway  I can do that?

**Comment by danielgtaylor** [comment]
@bclements that's very nice of you, thanks! I will add a Github Sponsor button to enable that, but nobody should feel like they need/should financially support the project.

I'll be honest, the project growth has been fantastic lately. The biggest issue I have is probably time, so other things that would help out are squashing bugs, doing code reviews, providing additional documentation and/or "how-to" content, and just spreading the word about the project (write blogs, go to conferences, record video demos, etc).

**Comment by danielgtaylor** [comment]
Here's the new button:

<img width="746" alt="Screenshot 2024-03-15 at 09 21 27" src="https://github.com/danielgtaylor/huma/assets/106826/674b9b38-6d8a-4737-aa31-014c6942d0b7">
