### ISSUE TITLE
Is there a feature to control how OpenAPI model names are generated ?

### ISSUE THREAD

**Issue by lsdch** [danielgtaylor/huma#322]
After going through the documentation, I now have an urge to make the switch from Gin+Swaggo to Huma. Thanks for the work on this nice piece of tech :pray:

I understand from the [first API](https://huma.rocks/tutorial/your-first-api/#operation) example in the docs that OpenAPI model definitions generated from response input/output body are generated as `{.TypeName}Body`. 
Is there any way to configure this behavior either globally or per response type (e.g. using struct tags) ?

Maybe something like : 
```go
type GreetingOutput struct {
	Body struct {
		Message string `json:"message" example:"Hello, world!" doc:"Greeting message"`
	} `model_name:"Greeting"` // name in OpenAPI spec
}
```

**Comment by danielgtaylor** [comment]
@lsdch it's not possible to do it per response using struct tags (though I think that's a great idea and we could add it), but you can set it globally in the registry. Huma ships with a default naming function:

https://pkg.go.dev/github.com/danielgtaylor/huma/v2#DefaultSchemaNamer

The schema namer functions take a type and a name hint, and return a generated name given those inputs. That in turn is used by the defaults like this:

https://github.com/danielgtaylor/huma/blob/main/defaults.go#L69

You can override it by creating your own config or overwriting the value in the default config, for example:

```go
func MyCustomSchemaNamer(t reflect.Type, hint string) string {
  return "..."
}

config := huma.DefaultConfig("My API", "1.0.0")
config.Components.Schemas = huma.NewMapRegistry("#/components/schemas", MyCustomSchemaNamer)
```

**Comment by lsdch** [comment]
Lovely. Definitely going to switch from Gin to Huma. I might submit a PR to support defining the model name using struct tags once I get familiar with the lib, but that might take a while.
