### ISSUE TITLE
Is there a way to view/generate the json schemas for my models?

### ISSUE THREAD

**Issue by bekabaz** [danielgtaylor/huma#326]
I have this in my huma.Config `SchemasPath:   "/schemas",` but when I navigate to /schemas I don't see anything. Is this expected? I need to be able to access the json schemas. I have read through https://huma.rocks/features/json-schema-registry/ but I don't see anything specific to my question.

**Comment by danielgtaylor** [comment]
@bekabaz each schema in the OpenAPI is exposed as a separate JSON Schema under the `/schemas` path. Take a look at your response to see the exact path, for example using the "greeting" example which uses `huma.DefaultConfig`:

```sh
$ restish :8888/greeting/bekabaz
HTTP/1.1 200 OK
Content-Length: 87
Content-Type: application/cbor
Date: Tue, 19 Mar 2024 15:31:09 GMT
Link: </schemas/GreetingOutputBody.json>; rel="describedBy"

{
  $schema: "http://localhost:8888/schemas/GreetingOutputBody.json"
  message: "Hello, bekabaz!"
}
```

Notice the `Link` header and `$schema` link in the response. If you follow that URL you will find:

```json
{
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "description": "A URL to the JSON Schema for this object.",
      "format": "uri",
      "readOnly": true,
      "type": "string"
    },
    "message": {
      "description": "Greeting message",
      "examples": [
        "Hello, world!"
      ],
      "type": "string"
    }
  },
  "required": [
    "message"
  ],
  "type": "object"
}
```

Every schema is exposed that way, including request body schemas. Take a look at your `/openapi.yaml` to find all the names under which they get exposed.

This is also what powers linting and completion as you type in e.g. VSCode when you edit resources in the API. It sees that `$schema` property, fetches the schema, and applies it to the document as you type, giving you errors if your changes aren't valid and providing suggestions for field names and documentation on hover. Stuff like this:

<p>
<img width="247" alt="Screenshot 2024-03-19 at 18 15 14" src="https://github.com/danielgtaylor/huma/assets/106826/7d7af58b-e91f-4d61-9fc8-b0acaccf9987"> <img width="221" alt="Screenshot 2024-03-19 at 18 15 31" src="https://github.com/danielgtaylor/huma/assets/106826/987a09e3-9b61-4863-b204-04468d578b2d"> <img width="398" alt="Screenshot 2024-03-19 at 18 15 47" src="https://github.com/danielgtaylor/huma/assets/106826/6e841f93-ab09-4439-ae4d-f62e254e0a6c">
</p>

**Comment by bekabaz** [comment]
Thank you once again. Closing this, I didn't opt to use the DefaultConfig so I was missing the transformer for the schema links.

**Comment by danielgtaylor** [comment]
@bekabaz BTW it's totally fine to not use the default config or transformer - those schemas still exist and can be fetched from the server. They just aren't advertised (that's all the transformer does). So if you know the model name there is no need for the transformer, though I think the VSCode support is nice for APIs with large/complex models that will be edited by hand.
