### ISSUE TITLE
hidden:"true" not working as expected

### ISSUE THREAD

**Issue by bekabaz** [danielgtaylor/huma#327]
I could have sworn this was working prior, but I don't have any screenshots of it to prove it. I have a response struct:

```
type AccountResponse2 struct {
	Body Account2
}

type Account2 struct {
	Id        int64  `json:"id" doc:"The ID of the resource."`
	Protected *string `json:"protected,omitempty" hidden:"true"`
}
```

The docs show this as the model for AccountResponse2
![image](https://github.com/danielgtaylor/huma/assets/7907379/bc34aec4-0978-4d96-aace-b6dd2dda082b)
I would have expected *Protected* to not show up at all.

It's totally possible I'm doing something wrong, but also could be a legit bug. Thoughts?

edit: i tried downgrading to v2.8.0 but it's the same thing so maybe this was always like this and I'm just noticing it

**Comment by danielgtaylor** [comment]
@bekabaz `hidden` only works for params currently: https://huma.rocks/features/request-validation/. It would be pretty easy to add support to the body schema generator to ignore fields with it set though. I'll leave this open as a feature request and can probably get to it later.

**Comment by bekabaz** [comment]
@danielgtaylor Took a stab at it and it's up for review [#328](https://github.com/danielgtaylor/huma/pull/328)
