### ISSUE TITLE
Streamlining Base Path Setup in OpenAPI Schemas

### ISSUE THREAD

**Issue by spa5k** [danielgtaylor/huma#331]
Currently, configuring base paths in OpenAPI schemas is a bit cumbersome. Simplifying this process by allowing direct usage of base paths like localhost:8008/api/v1 would greatly enhance user experience. It not only makes usage easier but also generates more concise code names, avoiding unwieldy ones like apiV1AuthGoogleCallbackGet.

https://swagger.io/docs/specification/api-host-and-base-path/

I suggest implementing a way to define the base path schema as the option while generating the huma instance.

**Comment by spa5k** [comment]
```go
humaConfig := huma.DefaultConfig("My API", "1")
	// Set basepath to localhost:8081/api/v1
	humaConfig.Servers = []*huma.Server{{ 
		URL:         "http://localhost:8081/api/v1",
		Description: "",
		Variables:   nil,
		Extensions:  nil,
	}}
	api := humachi.New(router, humaConfig)
```

Doing this results in urls like this ->
`http://localhost:8081/api/v1/api/v1/health` and it returns 404 obviously.

**Comment by spa5k** [comment]
Similar to how its done in swaggo 

```go
// @title           Swagger Example API
// @host      localhost:8080
// @BasePath  /api/v1
func main() {
	r := gin.Default()

	c := controller.NewController()

	v1 := r.Group("/api/v1")
	{
		accounts := v1.Group("/accounts")
		{
			accounts.GET(":id", c.ShowAccount)
		}
    //...
	}
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	r.Run(":8080")
}
```

**Comment by danielgtaylor** [comment]
This seems related to #305. I wonder if we can just:

1. Allow sub-routers / groups for all the adapters
2. Use the servers definition for the API base path/prefix to fetch the OpenAPI rather than a new config value

**Comment by danielgtaylor** [comment]
@spa5k FYI, I've opened up #338 to try and address some of this. Please take a look!

**Comment by spa5k** [comment]
This looks quite okay, we just need to make sure the basePath value is being set in correct way as it happens in swaggo.
