### ISSUE TITLE
How to upload big files?

### ISSUE THREAD

**Issue by ioppermann** [danielgtaylor/huma#333]
In the documenation it says that `Keep in mind that the body is read into memory before being passed to the handler function.` (https://huma.rocks/features/request-limits/).

How do I upload big files in a streaming manner, in order to avoid reading them completely into memory before processing them?

I tried

```go
type MediaUpload struct {
	RawBody io.Reader `contentType:"application/octet-stream"`
}

func process(data io.Reader) {
        // Process the data while reading
}

huma.Register(api, huma.Operation{
	OperationID:  "post-thing",
	Method:       http.MethodPost,
	Path:         "/media",
	Summary:      "Post a thing",
	MaxBodyBytes: 1024 * 1024 * 1024, // 1 GiB
}, func(ctx context.Context, input *MediaUpload) (*struct{}, error) {
        process(input.RawBody)
	return nil, nil
}
```

But this results in an internal server error.

**Comment by danielgtaylor** [comment]
@ioppermann if you need to handle very large files you can directly access the multipart form via `RawBody` as of today's [v2.10.0 release](https://github.com/danielgtaylor/huma/releases/tag/v2.10.0) as documented at https://huma.rocks/features/request-inputs/#multipart-form-data.

If that isn't sufficient, then remember you have full access to your underlying router and can bypass Huma for the file upload operation. Depends on what router you are using, but for `net/http` or Chi you can just use [`http.Request.FormFile(...)`](https://pkg.go.dev/net/http#Request.FormFile) directly which by default can use temporary files on disk when needed. If you aren't doing form uploads then you can access the `request.Body` reader directly and stream that to a temporary file as needed. Remember that Huma is meant to complement your router, not replace it!

**Comment by danielgtaylor** [comment]
I believe this question is answered, so I'm going to close as resolved, but please feel free to re-open or create a new issue if needed! Thanks.

**Comment by ioppermann** [comment]
Sorry for opening this again. I came back to this project and still have the same problem. I need access to the `request.Body` and I'm using Echo as router.

As I understand it, if I want the upload endpoint to be properly documented and validated (the endpoint also has query parameters), I need to use the `huma.Register` function where I also need to provide a handler for that endpoint. How do I get access to the `huma.Context` for that request in order to have access to the `request.Body`?

So far I worked around this by writing a middleware for Echo that puts the `echo.Context` into the `request.Context` as a value so I can access it in the Huma handler.

Is there a better way how to do it?

```go
type ContextConfig struct {
	Skipper middleware.Skipper
}

var DefaultContextConfig = ContextConfig{
	Skipper: middleware.DefaultSkipper,
}

func NewContext() echo.MiddlewareFunc {
	return NewContextWithConfig(DefaultContextConfig)
}

func NewContextWithConfig(config ContextConfig) echo.MiddlewareFunc {
	if config.Skipper == nil {
		config.Skipper = DefaultLoggerConfig.Skipper
	}

	return func(next echo.HandlerFunc) echo.HandlerFunc {
		return func(c echo.Context) error {
			if config.Skipper(c) {
				return next(c)
			}

			req := c.Request()

			ctx := context.WithValue(req.Context(), "echoctx", c)
			c.SetRequest(req.WithContext(ctx))

			return next(c)
		}
	}
}
```

```go
type MediaUpload struct {
   Tags string `query:"tags"`
}

func process(tags string, data io.Reader) error {
   // Process the data while reading
}

huma.Register(api, huma.Operation{
	Method:        gohttp.MethodPost,
	Path:          "/v1/media",
	DefaultStatus: 200,
	Errors:        []int{400, 413},
	Hidden:        false,
	Metadata:      map[string]any{},
	Tags:          []string{"media"},
	Summary:       "Upload media",
	Description:   "Upload media with tags",
	OperationID:   "v1-post-media",
	MaxBodyBytes:  -1,
	Parameters: []*huma.Param{
		{
			Name:        "tags",
			In:          "tags",
			Description: "Tags for this media",
			Required:    false,
			Example:     "tag1,tag2,tag3",
			Schema: &huma.Schema{
				Type: "string",
			},
		},
	},
	RequestBody: &huma.RequestBody{
		Description: "Data to be stored",
		Content: map[string]*huma.MediaType{
			"application/octet-stream": {
				Example: []byte("data"),
			},
		},
		Required: true,
	},
}, func(ctx context.Context, input *MediaUpload) (*struct{}, error) {
	var r io.Reader
	val := ctx.Value("echoctx")
	if val != nil {
		echoctx, ok := val.(echo.Context)
		if !ok {
			return nil, fmt.Errorf("invalid echo context available")
		}
		r = echoctx.Request().Body
	} else {
		r = bytes.NewReader(nil)
	}
	return nil, process(input.Tags)
})
```
