### ISSUE TITLE
Adding examples

### ISSUE THREAD

**Issue by bekabaz** [danielgtaylor/huma#337]
I encountered some issues when validating the generated spec on Swagger Editor. Reading through https://swagger.io/docs/specification/adding-examples/ shows that they want "example" for a single example, and "examples" for multiple examples. This generates Swagger Editor errors every time "examples" is used with one example:
```
Structural error at components.schemas....
should NOT have additional properties
additionalProperty: examples
```

This isn't an issue, but I wanted to point out that I also have used an escaped JSON string for an example on a map[string]interface{} field which is actually parsed correctly except for the "examples" issue noted above. Here's an example:
```
example:"{\"company\": \"tb\", \"city\":\"NY\", \"year\":2024}"
```
generates the following OpenAPI code:
```
examples:
         city: NY
         company: tb
         year: 2024
```

Manually changing all these to "example" in the Swagger Editor removes the errors, except obviously where we want multiple examples.

**Comment by danielgtaylor** [comment]
@bekabaz first off - thanks for being a sponsor! Much appreciated!

This is an interesting issue. I think the Swagger editor might be out of date or have a weird opinion on this. From the specs:

> Deprecated: The example property has been deprecated in favor of the JSON Schema examples keyword. Use of example is discouraged, and later versions of this specification may remove it.
> -- https://spec.openapis.org/oas/v3.1.0#fixed-fields-19

> [9.5. ](https://json-schema.org/draft/2020-12/json-schema-validation#section-9.5)["examples"](https://json-schema.org/draft/2020-12/json-schema-validation#name-examples)
> The value of this keyword MUST be an array. There are no restrictions placed on the values within the array. When multiple occurrences of this keyword are applicable to a single sub-instance, implementations MUST provide a flat array of all values rather than an array of arrays.
> -- https://json-schema.org/draft/2020-12/json-schema-validation#name-examples

> OpenAPI has a lot of places that can have an example, or multiple examples. OpenAPI v3.0 can have `example` or `examples` at the Media Type level (requests, responses, callbacks, and webooks) but it can also have a very different type of `example` inside the Schema Object. This schema object singular example was an OpenAPI-specific keyword which is no longer necessary now as JSON Schema has `examples`.
> -- https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0

So what I gather is this is new in Open API 3.1, and the recommendation is to _always_ use `examples` even for just a single item. You might open an issue with the Swagger folks to see if this is intentional behavior in the editor. Also are you using https://editor-next.swagger.io/? This seems to mark `example` as deprecated for me for OpenAPI 3.1 docs.

**Comment by bekabaz** [comment]
You're welcome, I'm having a lot of fun using Huma so far. Really helps that you are very responsive, figured it's the least I can do to show some appreciation.

 I see now that I was using https://editor.swagger.io/ which must be out of date with the latest OpenAPI spec. Looks good on https://editor-next.swagger.io/. Stoplight Studio wasn't showing any errors, this is probably why. Closing this, thanks for the help!
