### ISSUE TITLE
Is there a way to specify the order of the endpoints in stoplight programmatically

### ISSUE THREAD

**Issue by bclements** [danielgtaylor/huma#344]
I have one set of endpoints under the tag "Misc" I'd like this particular tag group of endpoints to be displayed dead last in the stoplight endpoint side menu.

Any thoughts or help would be appreciated.

**Comment by danielgtaylor** [comment]
@bclements you can use the OpenAPI top-level `tags` to set the sort order they show up in the documentation. For example:

```go
config := huma.DefaultConfig("Demo API", "1.0.0")
config.Tags = []*huma.Tag{
	{Name: "Foo", Description: "..."},
	{Name: "Bar", Description: "..."},
	{Name: "Misc", Description: "..."},
}
api = humago.New(mux, config)
```

**Comment by danielgtaylor** [comment]
Closing as I believe this was answered, but feel free to re-open if it's still an issue!
