### ISSUE TITLE
omitempty dictates field required-ness?

### ISSUE THREAD

**Issue by ssoroka** [danielgtaylor/huma#347]
Thanks for making Huma! it's the generics-first framework I wanted; I've built nearly the same thing elsewhere, and I'm happy to see this as I don't need to re-invent it again.

Just opening this for discussion/feedback.

Maybe I'm missing something here, but it seems like I need to use `omitempty`, eg `json:"field_name,omitempty"`, as an indicator of whether the field is optional in the api. This seems a bit strange, as:
- I was expecting it to be `validation:"required"`
- I usually think about `omitempty` being about how to format the generated json, rather than parsing input json.
- Looks like `*string` is also not enough to signal that the field is optional

**Comment by lazharichir** [comment]
Hey @ssoroka – we're discussing this in #351, so feel free to chip in with how you feel it should be implemented considering nullability and requiredness quirks in how it can be expressed in Go's type system vs JSON/Openapi.

**Comment by danielgtaylor** [comment]
This has been improved / addressed in #351, which is now merged in and will be release soon. There is a list of rules, but TL;DR: pointers set nullability, `omitempty` or `required` set optional/required.
