### ISSUE TITLE
Question: output open api config/html?

### ISSUE THREAD

**Issue by steeling** [danielgtaylor/huma#353]
Is it possible to render the open api config/html, so I can serve it outside of the binary? Are there convenience methods for this, outside of running the whole binary and manually querying the /docs path?

**Comment by danielgtaylor** [comment]
@steeling take a look at the spec-cmd example at https://github.com/danielgtaylor/huma/blob/main/examples/spec-cmd/main.go#L68-L76. You can run it with: 
```sh
$ go run . openapi >spec.yaml
```

That will dump it to a file without starting the server.
