### ISSUE TITLE
Duplicate Models

### ISSUE THREAD

**Issue by fritterhoff** [danielgtaylor/huma#37]
I just stumbled over this project. So far it looks great but I recognized one pretty 'ugly' point. 

In case of using a model twice e.g. encapsulated inside a slice and standalone the schema/model is redefined as ...2.

Is there an option to avoid this?
![image](https://user-images.githubusercontent.com/32478819/161915628-835900ca-04b5-4939-8efe-a6816ea0fd8d.png)

**Comment by danielgtaylor** [comment]
Huma v2's registry & schema generator now handle this nicely by generating a `$ref` to the model inside of an array by default. That behavior is customizable now as well, so if you have some other use-case in mind for how schemas get generated and referenced that is possible to set up too.
