### ISSUE TITLE
Register routes functionality with middlewares

### ISSUE THREAD

**Issue by aleksicmarija** [danielgtaylor/huma#378]
Just discussing. I had a little struggle adding one middleware to different handlers that have different input and output structs. I managed to do it, but I don't like all the wrapping and interfaces I needed to add to make it possible.

Wouldn't it be kinda cool to have a function that works like 'register', but it chains passed middlewares, including their own input, leading to a handler with their input and output?

If something like that already exists, I'm sorry!

**Comment by danielgtaylor** [comment]
@aleksicmarija do you have an example of what this would look like?

**Comment by quadgod** [comment]
Hi @aleksicmarija. I am also looking how to add middleware for specific route.

```go
huma.Register(app, huma.Operation{
  OperationID:   "registration",
  Method:        http.MethodPost,
  Tags:          []string{"account"},
  Path:          path,
  Summary:       "Register a new account",
  Description:   "Register a new account by email and password",
  DefaultStatus: http.StatusCreated,
}, func(ctx context.Context, input *RegistrationPayload) (*struct{}, error) {
  return nil, nil
}, ...here would be nice to have some code to register middleware)
```

**Comment by quadgod** [comment]
Hi @danielgtaylor 
I just dived deeper into docs and found resolvers.

I guess it's what all i need

```go
func (m *MyInput) Resolve(ctx huma.Context, prefix *huma.PathBuffer) []error {
  return []error{&huma.ErrorDetail{
    Message: "Foo has a bad value",
    Location: prefix.With("foo")
    Value: m.Foo,
  }}
}
```

**Comment by danielgtaylor** [comment]
@aleksicmarija @quadgod I've put up a proposed implementation at #382, let me know what you think. I opted to use the existing struct over adding variable arguments to all the registration functions so I'm curious if that works for you or why you might prefer other ways of doing it.
