### ISSUE TITLE
huma.NewError doesn't support error wrapping.

### ISSUE THREAD

**Issue by nunoo** [danielgtaylor/huma#380]
https://github.com/danielgtaylor/huma/blob/main/huma.go#L1280

Huma does a check if the error fits the interface, which prevents using wrapping. What are your thoughts on traversing the error tree using errors.Unwrap?

**Comment by nunoo** [comment]
or pass the raw error into the NewError method so we can unwrap ourselves

**Comment by danielgtaylor** [comment]
@nunoo thanks for pointing this out! I've opened a PR to enable wrapping so let me know if I missed anything.

**Comment by nunoo** [comment]
@danielgtaylor thanks so much for the quick response!
