### ISSUE TITLE
Add more tests for cookie

### ISSUE THREAD

**Issue by behnambm** [danielgtaylor/huma#388]
Hello,

I noticed that more tests can be written for `cookie`. Now the test coverage for `cookie` is `80.9%` but I can make it `100%`. 

Can I help with that? If so, any guidance would be appreciated.

**Comment by danielgtaylor** [comment]
@behnambm that would be great, go for it!

**Comment by robsonpeixoto** [comment]
What do you think about use https://about.codecov.io/ to track the code coverage, @danielgtaylor ?

**Comment by danielgtaylor** [comment]
@robsonpeixoto we already use it, see https://app.codecov.io/gh/danielgtaylor/huma. This is linked from the top of the README.
