### ISSUE TITLE
Add custom header from SSE Handler

### ISSUE THREAD

**Issue by kasfil** [danielgtaylor/huma#392]
How can I add custom header inside SSE handler?
i tried to attach inside response struct but no luck.
```go
type SseResponse struct {
    CustomHeader string `header:"X-Custom-Header"`
}

sse.Register(api, huma.Operation{
	Path:        "/sse",
	Method:      http.MethodGet,
	OperationID: "SseOperation",
	Summary:     "SSE Operation",
}, map[string]any{
	"test": SseResponse{},
}, func DashboardHandler(ctx context.Context, input *struct{}, send sse.Sender) {
    for {
        if err := send.Data(SseResponse{CustomHeader: "custom value"}); err != nil {
            return
        }
    )
})

```

**Comment by danielgtaylor** [comment]
@kasfil there's not really a built-in way to do this, and the `sse.Register` function is just a small wrapper around `huma.Register` meant as a convenience but may not cover all use-cases, so you have a couple of options:

1. You can use a [resolver](https://huma.rocks/features/request-resolvers/) to give you access to the `huma.Context` after input parsing to set some headers. Example: https://go.dev/play/p/gIRiDd0T6KM
2. You can implement your own version of `sse.Register` using the `huma.StreamResponse` like https://github.com/danielgtaylor/huma/blob/main/sse/sse.go#L117

Hope this helps!

**Comment by kasfil** [comment]
@danielgtaylor thanks for the advice.
I take the second option and that works great.

Again. Thanks for the advice and this awesome tool.

Should i close this issue?

**Comment by danielgtaylor** [comment]
Closing as resolved, thanks!
