### ISSUE TITLE
Allow custom Transform for nested objects

### ISSUE THREAD

**Issue by nunoo** [danielgtaylor/huma#404]
We implement the json.Marshaler interface on some objects that are present in some of our response bodies. However huma can't reasonably decipher what the final response looks like. Is there a way we could annotate a (nested) type either with an additional method to implement some interface so we can tell huma how to generate the docs?

The problem is go doesn't support embedding generics, so we implement Marshal to remove the intermediate field name. Huma optionally would never even need to call the method itself, just use it to determine the output type for documentation.

**Comment by danielgtaylor** [comment]
@nunoo have you tried implementing a `huma.SchemaProvider` for the type? See https://huma.rocks/features/schema-customization/#field-schema

**Comment by nunoo** [comment]
Thanks a lot that's exactly what I needed, I appreciate the quick response!
