### ISSUE TITLE
The validation of format:"email" is not perfect.

### ISSUE THREAD

**Issue by minpeter** [danielgtaylor/huma#446]
Email string `json:"email" doc:"Email of the user" format:"email"`

Validation was added and tested as above.
abc -> deny
abc@ -> deny
abc@a -> allow
abc@a. -> deny
acb@a.bc -> allow

Here I think it's strange that abc@a passes validation.

**Comment by minpeter** [comment]
Is this a valid email by rfc 5322?

I'm confused by the email verification standards that are different from usual.

**Comment by lazharichir** [comment]
These are indeed valid email addresses. You can use your own validation logic to further narrow down the emails you wish to accept.

See https://en.wikipedia.org/wiki/Email_address#Examples, specifically "admin@example"; or even https://stackoverflow.com/questions/20573488/why-does-html5-form-validation-allow-emails-without-a-dot for information.

**Comment by minpeter** [comment]
Thank you very much
