### ISSUE TITLE
Returning nil as response body causes 500

### ISSUE THREAD

**Issue by outofthisworld** [danielgtaylor/huma#484]
Some package level serialisation/reflection issue (I believe potentially to do with the SchemaLinkTransformer) is making a return of `nil` cause a 500 error as a response body.

Personally, I think this should be handled internally by the package to Serialise to null, to avoid redundant and unnecessary checking in every handler.

**Comment by danielgtaylor** [comment]
I believe this is a dupe of #544 and fixed in #546.
