### ISSUE TITLE
[Question] Length validation sptits out unicode charactors. Is there any way to avoid that?

### ISSUE THREAD

**Issue by rjshrjndrn** [danielgtaylor/huma#507]
![image](https://github.com/user-attachments/assets/fd5992d7-843b-40a5-84ef-742443ad4d90)

As you can see 
```go
	PhoneNumber *string    `json:"phoneNumber" doc:"Phone number of the user" minLength:"10" maxLength:"12"`
```
Validation failed, with some random string in the output message. Is there any way to mitigate that? 
Adding one step further 
is it possible to error out as `phoneNumber validation failed. minLength 10 maxLength 12`

**Comment by superstas** [comment]
Hey @rjshrjndrn 

`\u003e` means `>`  ( [U+003E](https://en.wikipedia.org/wiki/List_of_Unicode_characters) ) 

To get the error message like you described, try to implement a custom type with `ResolveWithPath` [method](https://pkg.go.dev/github.com/danielgtaylor/huma/v2#ResolverWithPath) 

Something like this ( I haven't tested )

```go

type PhoneNumber string

func (s PhoneNumber) Resolve(ctx huma.Context, prefix *huma.PathBuffer) []error {
	l := len(s)
	if l < 10 || l > 12 {
		return []error{&huma.ErrorDetail{
			Location: prefix.With("phoneNumber"),
			Message:  "phoneNumber validation failed. minLength 10 maxLength 12",
			Value:    s,
		}}
	}

	return nil
}

...
PhoneNumber PhoneNumber `json:"phoneNumber,omitempty" doc:"Phone number of the user" minLength:"10" maxLength:"12"`

```
