### ISSUE TITLE
Question: Is is possible for field order in documentation to reflect struct field order?

### ISSUE THREAD

**Issue by darrenparkinson** [danielgtaylor/huma#521]
Hi,

Is it possible to view the fields for the body of a request in the order they're defined in the struct rather than alphabetically?

Perhaps this is more a question for stoplight?

Many thanks for any feedback you can provide.

**Comment by danielgtaylor** [comment]
@darrenparkinson I'm not sure how Stoplight Elements or other documentation renderers handle this, but from the Huma and Go side of things I can explain what's happening. The Go struct fields are inspected by Huma and a JSON Schema is generated within the OpenAPI document. The JSON Schema has a type of `object` and a field `properties` which is an object (Go `map`) of each field name from the struct to a schema describing each field.

That then gets serialized as JSON/YAML. Go's JSON marshaler states:

> Map values encode as JSON objects. The map's key type must either be a string, an integer type, or implement [encoding.TextMarshaler](https://pkg.go.dev/encoding#TextMarshaler). The map keys are sorted and used as JSON object keys by applying the following rules, subject to the UTF-8 coercion described for string values above:
>
> - keys of any string type are used directly
> - [encoding.TextMarshalers](https://pkg.go.dev/encoding#TextMarshalers) are marshaled
> - integer keys are converted to strings

**Comment by darrenparkinson** [comment]
Thanks, yeah, that makes sense. It's interesting since the "required" array in the openapi.json file is in the original order, but the properties are sorted. As you say, it's the use of map that appears to be affecting that and not a lot I can do about it, short of rearranging them in the openapi file 😆. https://go.dev/play/p/fsmdoq1FaWk
