### ISSUE TITLE
500 errors with "cannot read request body"

### ISSUE THREAD

**Issue by nunoo** [danielgtaylor/huma#522]
We're getting 500 errors with `cannot read request body`, which seems to come from this [line](https://github.com/danielgtaylor/huma/blob/main/huma.go#L1216). I'm unable to recreate this on demand currently, so not sure if its a weird client request coming through or some other issue. I am surprised to see no err check for `io.EOF` though so wondering if its that? If not, have you seen these types of issues, and know what might cause them? We're logging the returned error, and it looks somewhat empty:
```
errors: [
   0: {}
]
level: "ERROR"
message: "cannot read request body"
msg: "returning error"
```
We're using humago adapter

**Comment by danielgtaylor** [comment]
@nunoo sorry I have not run into this. We mainly use the `humachi` adapter, but underneath the hood it uses the same underlying standard library HTTP functionality. I don't think you need to check for `io.EOF` as described in the [docs for `io.Copy`](https://pkg.go.dev/io#Copy):

> A successful Copy returns err == nil, not err == EOF. Because Copy is defined to read from src until EOF, it does not treat an EOF from Read as an error to be reported.

Happy to dig in more if you can provide a way to repro, but at this point I don't know how to debug this unfortunately.
