### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by rene-xompass** [danielgtaylor/huma#53]
Hi guys.
Your project looks really cool.
Due to performance issues, I need to migrate an api in NodeJS (loopback) to Go, and in the search I found Huma, which has most of the things I need. However, I have only found references to the framework on a couple of sites.

Is the project ready to be used in production?
Are there long plans in its development?

I'm pretty new to golang, but if I can help with anything, let me know.

**Comment by danielgtaylor** [comment]
@rene-xompass @hagemt it is production-ready in the sense that it is already being used in production for multiple services at a large media company, but the development is ongoing and the framework is fairly young. We are fixing bugs as we find them and adding features as we need them. I would love for some people to harden and add features as necessary for their use-cases.
