### ISSUE TITLE
Enum validation tag with comma in actual values

### ISSUE THREAD

**Issue by andersarpi** [danielgtaylor/huma#535]
Hi,

Is there some way to add an enum validation tag where the enumerated string values contain commas in them? E.g. in the following example I want `Maybe, not sure` to be seen as a single allowed value.

```
type input struct {
	Value string `enum:"Yes,No,Maybe, not sure'"`
}
```

I feel like I'm either missing something obvious or it's simply not possible at the moment.

Thanks a lot for a great library!

**Comment by danielgtaylor** [comment]
@andersarpi unfortunately this isn't currently possible via the struct field tag. The code uses a simple string split, see https://github.com/danielgtaylor/huma/blob/main/schema.go#L534.

As a workaround, after registering your operation you can manually add the option. Something like:

```go
api.OpenAPI().Paths["/my/operation"].Get.Responses["200"].Content["application/json"].Schema.Properties["Value"].Enum = []string{"Yes", "No", "Maybe, not sure"}
```

Alternatively you could use a schema provider or transformer to do something similar by creating a custom type wrapping a string. https://huma.rocks/features/schema-customization/#field-schema
