### ISSUE TITLE
returning nil for both the output struct and the error from a handler panics

### ISSUE THREAD

**Issue by guneyizol** [danielgtaylor/huma#544]
Hello ✋ 

Below code panics because both the response and the error are returned as nil. Is this a feature or a bug? IMHO handling this case gracefully would be better for UX.

Thanks 🙏 

```go
mux := http.NewServeMux()

api := humago.New(mux, huma.DefaultConfig("My API", "1.0.0"))

huma.Register(
	api,
	huma.Operation{
		Method: http.MethodPost,
		Path:   "/",
	},
	func(ctx context.Context, input *Input) (*Output, error) {
		return nil, nil
	}
)
```

**Comment by danielgtaylor** [comment]
@guneyizol thanks for reporting! I've thrown up a quick PR to fix this.
