### ISSUE TITLE
[Question]: Is it possible to change default HTTP Status Code on Validation Error?

### ISSUE THREAD

**Issue by superstas** [danielgtaylor/huma#561]
Hi there!

I wonder how to change the default HTTP Status Code from `422` ( from [here](https://github.com/danielgtaylor/huma/blob/main/huma.go#L1180) ) to smth custom ( in our case, it's `400` ).

With the current capabilities, I can customize almost everything in the default validation error by overriding `huma.NewError` function and get what I need:

```sh
        HTTP/1.1 422 Unprocessable Entity
        Connection: close
        Content-Type: application/problem+json
        
        {
          "type": "bad-request/validation",
          "title": "Bad Request",
          "status": 400,
          "detail": "Validation failed",
          "errors": [
            {
              "message": "required header parameter is missing",
              "location": "header.X-Custom-Header",
              "value": ""
            }
          ]
        }
```

However, I couldn't find a way to customize the HTTP Status Code for this case.
Could you please help me understand whether it's possible? If not, what do you think about implementing it? Does it make any sense?

Thank you.

**Comment by yalagtyarzh** [comment]
Same problem, help please

**Comment by superstas** [comment]
@danielgtaylor thank you!
