### ISSUE TITLE
Dependency Error while installing huma

### ISSUE THREAD

**Issue by nishant8568** [danielgtaylor/huma#569]
Dependency on `IASM` repo is throwing an error:
`github.com/chenzhuoyu/iasm@v0.9.1: reading github.com/chenzhuoyu/iasm/go.mod at revision v0.9.1: unknown revision v0.9.1`

**Comment by derekssmith** [comment]
I am having the same issue. Any ideas?

**Comment by danielgtaylor** [comment]
This seems to affect the gin adapter. https://github.com/chenzhuoyu/iasm/issues/2
