### ISSUE TITLE
Modify the Content-Type in the Header within the Transformer to enable Formats to take effect.

### ISSUE THREAD

**Issue by learning-go123** [danielgtaylor/huma#635]
I want to modify the Content-Type in the Header within the Transformer. For example, in the following code:

```go
func TestTransformer(ctx huma.Context, status string, v any) (any, error) {
    ctx.SetHeader("Content-Type", "text/html")
    return v, nil
}
```
I used the code above, but the Formats did not take effect. I checked the Huma source code, and modifying the Content-Type after the Transformer does not work.

Is there a way to modify the Content-Type within the Transformer so that text/html in Formats will take effect?

**Comment by danielgtaylor** [comment]
@learning-go123 this isn't currently possible. It could maybe be added as a feature but the complication from a cursory glance is that the context's written headers cannot be read out later so it might require modifying the context interface. Is there a reason you don't want to use client-driven content negotiation for this? I.e. the client would send `Accept: text/html` and then Huma will use that format when replying to that client.

**Comment by learning-go123** [comment]
@danielgtaylor In the case of supporting two return formats, HTML and JSON, sometimes I want to quickly verify the data format in the browser. Add parameters to the URL query to dynamically modify the returned data format

**Comment by danielgtaylor** [comment]
@learning-go123 you could use a middleware for this, converting a query param into the `Accept` header and then you can use either the header or query param for testing. Here's a runnable example:

https://go.dev/play/p/6xmG_IqxuAr

The main parts are this middleware to convert into the header:

```go
func formatMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// If a format query parameter is present, set the Accept header. This lets
		// you request a specific format from e.g. a browser for testing.
		if format := r.URL.Query().Get("format"); format != "" {
			r.Header.Set("Accept", format)
		}
		next.ServeHTTP(w, r)
	})
}
```

And then setting up a new format and letting the user pick it:

```go
config := huma.DefaultConfig("Demo", "1.0.0")
config.Formats["application/yaml"] = huma.Format{
	Marshal: func(writer io.Writer, v any) error {
		// Return YAML using Huma's built-in JSON-to-YAML conversion
		b, err := json.Marshal(v)
		if err == nil {
			err = yaml.Convert(writer, bytes.NewReader(b))
		}
		return err
	},
}
```

**Comment by learning-go123** [comment]
Thank you very much for your patience and help. The issue has been resolved. Apologies for getting stuck in a misconception—I realized I can modify the Accept header in the net/http route.
