### ISSUE TITLE
huma.Operation.Callbacks usage is unclear

### ISSUE THREAD

**Issue by wttw** [danielgtaylor/huma#653]
I'm unsure how to add a path to a callback entry.

I'm expecting the generated schema to look something like:

```
paths:
  /create:
    post:
      callbacks:
        myEvent:
          "{$request.body#/callbackUrl}":
            post:
              requestBody: # Contents of the callback message
                …
```

But huma.Operation.Callbacks is a `map[string]*huma.PathItem` and I don't see any way to include a path.

I get something like this, instead:

```
paths:
  /create:
    post:
      callbacks:
        myEvent:
          post:
            requestBody: # Contents of the callback message
              …
```

I couldn't find any sample or test code using Callbacks or Webhooks, so I'm not sure whether this is broken or whether I'm holding it wrong.

**Comment by danielgtaylor** [comment]
@wttw you are right, this is a bug. It should be `map[string]map[string]*huma.PathItem`.

https://spec.openapis.org/oas/v3.1.1.html#callback-object
https://www.speakeasy.com/post/openapi-tips-webhooks-callbacks#creating-a-callback-in-openapi

Thanks for pointing this out, I totally missed that. The original spec explanation is a bit confusing and didn't provide an example 😞
