### ISSUE TITLE
unsupported param type uuid.UUID

### ISSUE THREAD

**Issue by jclem** [danielgtaylor/huma#654]
If I have a custom type, such as a UUID, is it possible to use it in path parameters? For example, I'd like to just have it parsed from the string and return a 400 on invalid values, rather than having to parse every UUID manually in my request handlers.

**Comment by krisatverbidio** [comment]
Yes, it works as expected for me. I'm using  `github.com/google/uuid` for UUIDs

```
huma.Register(a.api, huma.Operation{
        OperationID: "get-device-by-id",
        Method:      http.MethodGet,
        Path:        "/devices/{device_id}",
        [...]   
}    
```

And then this is the input struct definition:

```
type GetDeviceInput struct {
	DeviceID uuid.UUID `path:"device_id" doc:"device id"`
}
```

**Comment by danielgtaylor** [comment]
@jclem yes it should work, as mentioned above. Under the hood this works by supporting anything that implements [`encoding.TextUnmarshaler'](https://pkg.go.dev/encoding#TextUnmarshaler) from the standard library. If you create custom types and want them to be supported out-of-the-box, just implement that method on them and it should all just work!
