### ISSUE TITLE
Is there a way to register custom Schemas without registering an operation?

### ISSUE THREAD

**Issue by Blinkuu** [danielgtaylor/huma#670]
I'm implementing a WebSockets API and would like to include my custom message types as part of my OpenAPI specification so it's easier for clients to consume.

How could I do it with Huma?

**Comment by lazharichir** [comment]
We use a custom namer for some reasons (we added a struct tag to hardcode, sometimes, the name of the schema) so here is how I do it:

```golang
package openapiregistry

var Registry = huma.NewMapRegistry("#/components/schemas/", MyCustomSchemaNamer)

func init() {
	Registry.Map()["AnyAction"] = &huma.Schema{Type: "string", Enum: actions.AllAsAny()}
	// ... more of these ...
}

func MyCustomSchemaNamer(t reflect.Type, hint string) string {
	// our custom namer, there's a default one you can use
}
```


``` golang
// when instantiating our API
humaConfig := huma.DefaultConfig("Name of our API", "1.0.0")
humaConfig.OpenAPI.Components.Schemas = openapiregistry.Registry
```

I understand you could use the default registry with something like:

```golang
humaConfig.OpenAPI.Components.Schemas.Map()["AnyAction"] = &huma.Schema{Type: "string", Enum: actions.AllAsAny()} 
```

**Comment by danielgtaylor** [comment]
@Blinkuu, thanks for the question. @lazharichir is right you can manually add schemas like in his example. Here is one you can run showing how it works: https://go.dev/play/p/DRcb_umQhX1. Hope this helps!

**Comment by Blinkuu** [comment]
Thanks, I got it working, closing the issue :)
