### ISSUE TITLE
Access to Request

### ISSUE THREAD

**Issue by mtiller** [danielgtaylor/huma#84]
I see that the `huma.Context` has the request contained in it.  But it doesn't expose this.  So, for example, if I want to handle content negotiation on my own (because `huma`'s logic isn't sufficient), I cannot get access to the underlying request nor its headers (from what I can see).

Would you accept a PR that exposes the request via a method?

**Comment by mtiller** [comment]
I noticed that you can use a header parameter in your handler input to access things like header values.  But I wonder if this kind of "escape hatch" might still be useful?

**Comment by danielgtaylor** [comment]
You might try using a resolver function, which gives you full access to the incoming request. See https://github.com/danielgtaylor/huma#resolvers

**Comment by mt35-rs** [comment]
OK.  So I think my use cases are addressed with the existing functionality.  So I'll close this ticket.  One idea for the future could be to inject it if there are any entities of type `*http.Request` in the `input` struct, _e.g.,_

```go
type MyInput struct {
	Host   string
	Name string `query:"name"`
	Request *http.Request // Populate with the request, if present
}
```

Just a thought in case this comes up again.

Thanks.
