### ISSUE TITLE
Server Sent Events

### ISSUE THREAD

**Issue by mtiller** [danielgtaylor/huma#88]
I was looking for a way for `huma` resources to implement [Server Sent Events](https://gist.github.com/lotusirous/2a40a23469a7b0f7870698bbe528ea1e).  In that example, they see if the response writer conforms to the `Flusher` interface.  If it does, there is no problem.  But I've tried that with `huma.Context` and it does not conform to the `Flusher` interface.  As a result, it isn't possible to flush the events as they are generated.

Any suggestions here?

**Comment by mtiller** [comment]
A related question would be how to integrate websockets, should the need arise?

**Comment by danielgtaylor** [comment]
@mtiller this is something I've been meaning to look into as we may start using SSE in the next few months as well. I don't know whether it is currently possible (it seems like it's not) so maybe we need to add `Flusher` to the `huma.Context` interface as a first step.

**Comment by mt35-rs** [comment]
What I don't quite get is why the `ResponseWriter` doesn't _already_ implement the `Flusher` interface.  I'm pretty sure I read that `http.ResponseWriter` does but it is possible that it could be wrapped by something that doesn't.  But I didn't see any case where `huma` was wrapping it.  Just ensuring that the `ResponseWriter` that is used to compose `huma.Context` would be sufficient presumably.  I wonder if simply nesting the `ResponseWriter` is somehow interfering with the ability to cast it to `Flusher`?

**Comment by mt35-rs** [comment]
I've added a pull request (#89) that resolves this.  If you could merge this, my tests indicate that SSE should work at that point.

**Comment by danielgtaylor** [comment]
Closing as this was resolved in #89 for Huma v1, and Huma v2 has an `sse` package to enable this functionality at a higher level.
